/**
 * Document Template Registry
 *
 * Defines the exact structure, required sections, and regulatory references
 * for every document type across all 10 Protekon verticals.
 *
 * The AI generator fills in the CONTENT. The template locks the STRUCTURE.
 * This guarantees consistent outputs regardless of how many times a document
 * is generated — same sections, same order, same regulatory references.
 *
 * Usage:
 *   const template = getDocumentTemplate("construction", "wvpp")
 *   // Pass template.sections to the AI as required output structure
 *   // AI fills in section.body for each section
 *   // PDF renderer uses template.sections in order
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SectionTemplate = {
  /** Section heading — rendered as-is in the PDF. AI does NOT rename this. */
  heading: string
  /** What this section must cover — injected into the AI prompt as instructions. */
  purpose: string
  /** Specific regulatory references that MUST appear in this section's content. */
  requiredReferences: string[]
  /** Estimated word count for the AI to target. */
  targetWords: number
  /** If true, this section is included even when no gap exists for it. */
  alwaysInclude: boolean
}

export type DocumentTemplate = {
  /** Machine-readable document type ID. Stored in documents.type column. */
  id: string
  /** Human-readable title rendered in PDF header. */
  title: string
  /** Which vertical this template belongs to. "all" = cross-vertical. */
  vertical: string
  /** Document description for the knowledge base / UI. */
  description: string
  /** Primary regulatory authority for this document. */
  jurisdiction: "cal-osha" | "federal-osha" | "hipaa" | "dot" | "cslb" | "dpr" | "multi"
  /** Required client data fields — generator will error if these are missing. */
  requiredClientFields: string[]
  /** Ordered section templates — the AI fills content within this structure. */
  sections: SectionTemplate[]
  /** Footer disclaimer text for the PDF. */
  disclaimer: string
  /** How often this document should be refreshed. */
  refreshCycle: "annual" | "semi-annual" | "quarterly" | "on-change" | "one-time"
  /** Minimum retention period in years. */
  retentionYears: number
}

// ---------------------------------------------------------------------------
// Cross-Vertical Templates (apply to all verticals)
// ---------------------------------------------------------------------------

const WVPP_TEMPLATE: DocumentTemplate = {
  id: "wvpp",
  title: "Workplace Violence Prevention Plan",
  vertical: "all",
  description: "Site-specific WVPP required by California SB 553 (Labor Code §6401.9). Applies to all employers with 10+ employees.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This plan was generated by Protekon based on the client's intake data and Cal/OSHA Model WVPP framework. It must be reviewed by the responsible person identified in Section 1 and updated whenever site conditions or personnel change.",
  sections: [
    {
      heading: "1. Responsible Persons",
      purpose: "Identify the person(s) responsible for implementing the WVPP. Must include name/title of the person with authority and responsibility for the plan.",
      requiredReferences: ["Labor Code §6401.9(b)(1)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "2. Employee Involvement",
      purpose: "Describe how employees are involved in developing, implementing, and reviewing the WVPP. Must include the mechanism for employee input (e.g., safety committee, anonymous reporting, direct feedback).",
      requiredReferences: ["Labor Code §6401.9(b)(2)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. Workplace Violence Hazard Identification and Evaluation",
      purpose: "Describe how workplace violence hazards are identified and evaluated. Must include initial assessment results, environmental risk factors (lighting, layout, public access), and staffing-related risk factors.",
      requiredReferences: ["Labor Code §6401.9(b)(3)", "8 CCR 3203(a)(4)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "4. Hazard Correction",
      purpose: "Describe procedures to correct identified hazards in a timely manner. Must include both immediate interim measures and long-term corrective actions.",
      requiredReferences: ["Labor Code §6401.9(b)(4)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Incident Response Procedures",
      purpose: "Describe how the employer responds to actual or potential workplace violence emergencies. Must include communication protocols, evacuation procedures, law enforcement contact procedures, and medical response.",
      requiredReferences: ["Labor Code §6401.9(b)(5)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "6. Post-Incident Response and Investigation",
      purpose: "Describe procedures for post-incident response, including investigation procedures, support for affected employees, and corrective action identification.",
      requiredReferences: ["Labor Code §6401.9(b)(6)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Training Requirements",
      purpose: "Describe the training program including initial training for new employees, annual refresher training, and additional training when the plan is updated. Training must be interactive and specific to this worksite.",
      requiredReferences: ["Labor Code §6401.9(b)(7)", "Labor Code §6401.9(e)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "8. Incident Log Procedures",
      purpose: "Describe how workplace violence incidents are logged, including the Violent Incident Log format, required data fields per §6401.9(d), PII protections, 5-year retention, and employee access rights (15 calendar days).",
      requiredReferences: ["Labor Code §6401.9(d)", "Labor Code §6401.9(d)(2)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "9. Plan Review and Updates",
      purpose: "Describe the schedule and triggers for reviewing and updating this plan. Must include annual review, post-incident review, and review when workplace conditions change.",
      requiredReferences: ["Labor Code §6401.9(b)(8)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

const IIPP_TEMPLATE: DocumentTemplate = {
  id: "iipp",
  title: "Injury and Illness Prevention Program",
  vertical: "all",
  description: "Site-specific IIPP required by Cal/OSHA (8 CCR §3203). Every California employer must maintain a written, site-specific IIPP.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This IIPP was generated by Protekon based on the client's worksite data and Cal/OSHA requirements under 8 CCR §3203. It must be reviewed annually and updated when conditions change.",
  sections: [
    {
      heading: "1. Responsible Person",
      purpose: "Identify the person with authority and responsibility for implementing the IIPP. Name and title required.",
      requiredReferences: ["8 CCR 3203(a)(1)"],
      targetWords: 150,
      alwaysInclude: true,
    },
    {
      heading: "2. Compliance System",
      purpose: "Describe how the employer ensures employee compliance with safe work practices. Must include recognition programs, disciplinary procedures, and supervisor accountability.",
      requiredReferences: ["8 CCR 3203(a)(2)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. Communication System",
      purpose: "Describe how safety information is communicated to employees. Must include the method (meetings, bulletin boards, written communications) and how employees can report hazards without fear of reprisal.",
      requiredReferences: ["8 CCR 3203(a)(3)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "4. Hazard Identification and Evaluation",
      purpose: "Describe procedures for identifying and evaluating workplace hazards. Must include initial assessment, periodic inspections, and assessment when new substances/processes/equipment are introduced.",
      requiredReferences: ["8 CCR 3203(a)(4)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "5. Hazard Correction",
      purpose: "Describe procedures for correcting identified hazards in a timely manner. Must include interim protective measures when a hazard cannot be immediately corrected.",
      requiredReferences: ["8 CCR 3203(a)(6)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "6. Accident/Exposure Investigation",
      purpose: "Describe procedures for investigating workplace accidents and exposures. Must include investigation procedures, root cause analysis, and corrective action documentation.",
      requiredReferences: ["8 CCR 3203(a)(5)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Training and Instruction",
      purpose: "Describe the employee training program. Must include training for new employees, training when new hazards are introduced, and training for supervisors. Must be specific to this worksite's hazards.",
      requiredReferences: ["8 CCR 3203(a)(7)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "8. Recordkeeping",
      purpose: "Describe how safety records are maintained including inspection records, training documentation, and hazard correction records.",
      requiredReferences: ["8 CCR 3203(b)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

const EMERGENCY_ACTION_PLAN_TEMPLATE: DocumentTemplate = {
  id: "eap",
  title: "Emergency Action Plan",
  vertical: "all",
  description: "Written emergency action plan required by Cal/OSHA (8 CCR §3220). Covers fire, earthquake, active threat, and medical emergencies.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This EAP was generated by Protekon. It must be reviewed with all employees upon initial assignment and whenever the plan changes.",
  sections: [
    {
      heading: "1. Emergency Escape Procedures and Routes",
      purpose: "Describe evacuation routes, assembly points, and exit assignments. Must be specific to the worksite layout.",
      requiredReferences: ["8 CCR 3220(a)(1)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Critical Operations Shutdown Procedures",
      purpose: "Identify employees assigned to shut down critical operations before evacuation and the procedures they follow.",
      requiredReferences: ["8 CCR 3220(a)(2)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "3. Employee Headcount Procedures",
      purpose: "Describe how employees are accounted for after evacuation.",
      requiredReferences: ["8 CCR 3220(a)(3)"],
      targetWords: 150,
      alwaysInclude: true,
    },
    {
      heading: "4. Rescue and Medical Duties",
      purpose: "Identify employees assigned to perform rescue or medical duties and their training requirements.",
      requiredReferences: ["8 CCR 3220(a)(4)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "5. Emergency Reporting Procedures",
      purpose: "Describe how emergencies are reported including fire, medical, active threat, and natural disaster.",
      requiredReferences: ["8 CCR 3220(a)(5)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Emergency Contact Information",
      purpose: "List emergency contacts including 911, local fire, local police, poison control, and internal emergency contacts.",
      requiredReferences: ["8 CCR 3220(a)(6)"],
      targetWords: 150,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Construction-Specific Templates
// ---------------------------------------------------------------------------

const FALL_PROTECTION_PLAN_TEMPLATE: DocumentTemplate = {
  id: "fall-protection-plan",
  title: "Fall Protection Plan",
  vertical: "construction",
  description: "Site-specific fall protection plan. #1 Cal/OSHA citation in construction.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "on-change",
  retentionYears: 5,
  disclaimer: "This fall protection plan must be reviewed whenever work conditions or locations change. A competent person must be designated to implement this plan on each jobsite.",
  sections: [
    {
      heading: "1. Fall Hazard Identification",
      purpose: "Identify all fall hazards at the worksite including open sides/edges, holes, leading edges, and elevated work surfaces above 7.5 feet.",
      requiredReferences: ["8 CCR 1509(a)", "8 CCR 1504"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Fall Protection Systems",
      purpose: "Describe the fall protection systems used — guardrails, safety nets, personal fall arrest systems. Must specify which system is used for each identified hazard.",
      requiredReferences: ["8 CCR 1509(b)", "8 CCR 1510"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "3. Competent Person Designation",
      purpose: "Identify the competent person responsible for fall protection on each jobsite. Must include qualifications.",
      requiredReferences: ["8 CCR 1509(a)"],
      targetWords: 150,
      alwaysInclude: true,
    },
    {
      heading: "4. Training Requirements",
      purpose: "Describe fall protection training including hazard recognition, equipment use, and rescue procedures.",
      requiredReferences: ["8 CCR 1509(d)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Rescue Procedures",
      purpose: "Describe how a worker in a fall arrest system will be rescued promptly. Must address self-rescue, assisted rescue, and suspension trauma.",
      requiredReferences: ["8 CCR 1511.1"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "6. Equipment Inspection and Maintenance",
      purpose: "Describe inspection schedules for fall protection equipment. Damaged equipment removal procedures.",
      requiredReferences: ["8 CCR 1509(c)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Healthcare-Specific Templates
// ---------------------------------------------------------------------------

const BBP_EXPOSURE_CONTROL_PLAN_TEMPLATE: DocumentTemplate = {
  id: "bbp-exposure-control",
  title: "Bloodborne Pathogen Exposure Control Plan",
  vertical: "healthcare",
  description: "Required exposure control plan for workplaces with occupational exposure to blood or other potentially infectious materials.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This Exposure Control Plan must be reviewed and updated annually, and whenever new tasks or procedures affect occupational exposure.",
  sections: [
    {
      heading: "1. Exposure Determination",
      purpose: "List all job classifications with occupational exposure to blood/OPIM. Include classifications where ALL employees have exposure and classifications where SOME employees have exposure (with task list).",
      requiredReferences: ["8 CCR 5193(c)(2)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Methods of Implementation and Control",
      purpose: "Describe universal precautions, engineering controls (sharps containers, needleless systems), work practice controls (hand washing, handling sharps), and PPE requirements.",
      requiredReferences: ["8 CCR 5193(d)(1)", "8 CCR 5193(d)(2)", "8 CCR 5193(d)(3)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "3. Hepatitis B Vaccination Program",
      purpose: "Describe the hepatitis B vaccination program offered to all employees with occupational exposure at no cost within 10 working days of assignment.",
      requiredReferences: ["8 CCR 5193(f)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "4. Post-Exposure Evaluation and Follow-Up",
      purpose: "Describe procedures following an exposure incident including documentation, medical evaluation, counseling, and source individual testing.",
      requiredReferences: ["8 CCR 5193(f)(3)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "5. Sharps Injury Log",
      purpose: "Describe the sharps injury log maintained for recording percutaneous injuries from contaminated sharps.",
      requiredReferences: ["8 CCR 5193(h)(5)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Training",
      purpose: "Describe initial and annual BBP training. Must include epidemiology, transmission modes, exposure control plan overview, recognition of exposure situations, and post-exposure procedures.",
      requiredReferences: ["8 CCR 5193(g)(2)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Recordkeeping",
      purpose: "Describe medical records (duration of employment + 30 years), training records (3 years), and sharps injury log retention.",
      requiredReferences: ["8 CCR 5193(h)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Manufacturing-Specific Templates
// ---------------------------------------------------------------------------

const LOTO_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "loto-program",
  title: "Lockout/Tagout (LOTO) Program",
  vertical: "manufacturing",
  description: "Energy control program for servicing and maintenance of machines and equipment where unexpected energization could cause injury.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Machine-specific LOTO procedures must be developed for each piece of equipment. This program establishes the overall framework. Equipment-specific procedures are generated separately.",
  sections: [
    {
      heading: "1. Purpose and Scope",
      purpose: "Define which machines, equipment, and energy sources are covered. Identify all energy types present (electrical, mechanical, hydraulic, pneumatic, chemical, thermal, gravitational).",
      requiredReferences: ["8 CCR 3314(a)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "2. Authorized and Affected Employees",
      purpose: "Define authorized employees (who perform LOTO), affected employees (who operate machines being locked out), and other employees (who work in the area). List by job title.",
      requiredReferences: ["8 CCR 3314(b)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "3. Lockout/Tagout Procedure — Step by Step",
      purpose: "The sequence: 1) Notify affected employees, 2) Shut down equipment, 3) Isolate energy sources, 4) Apply locks/tags, 5) Verify zero energy state, 6) Perform work, 7) Remove locks/tags, 8) Notify and restart.",
      requiredReferences: ["8 CCR 3314(c)", "8 CCR 3314(d)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "4. Lock and Tag Specifications",
      purpose: "Describe the locks and tags used. Must be durable, standardized, substantial enough to prevent removal without excessive force, and identify the authorized employee who applied them.",
      requiredReferences: ["8 CCR 3314(c)(5)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "5. Group Lockout/Tagout Procedures",
      purpose: "Procedures when multiple employees are servicing the same equipment. Must ensure each employee has individual lockout protection.",
      requiredReferences: ["8 CCR 3314(f)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Training and Certification",
      purpose: "Training requirements for authorized, affected, and other employees. Retraining triggers. Certification records.",
      requiredReferences: ["8 CCR 3314(g)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "7. Periodic Inspection",
      purpose: "Annual inspection of energy control procedures by an authorized employee who is NOT the one using the procedure being inspected.",
      requiredReferences: ["8 CCR 3314(e)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Agriculture-Specific Templates
// ---------------------------------------------------------------------------

const HEAT_ILLNESS_PREVENTION_PLAN_TEMPLATE: DocumentTemplate = {
  id: "heat-illness-prevention",
  title: "Heat Illness Prevention Plan",
  vertical: "agriculture",
  description: "Required heat illness prevention plan for outdoor workers. Cal/OSHA's most enforced agricultural standard.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This plan must be available at the worksite at all times. Supervisors and employees must be trained before beginning outdoor work.",
  sections: [
    {
      heading: "1. Water Provision",
      purpose: "Describe how fresh, pure, suitably cool drinking water is provided to employees free of charge. Must be located as close as practicable to work areas. Quantity: enough for each employee to drink 1 quart per hour.",
      requiredReferences: ["8 CCR 3395(c)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "2. Shade Access",
      purpose: "Describe shade structures available when temperatures exceed 80°F. Shade must be open to air or ventilated, located as close as practicable, and accommodate all employees on recovery or rest periods at the same time.",
      requiredReferences: ["8 CCR 3395(d)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. High-Heat Procedures (95°F+)",
      purpose: "Additional procedures when temperatures reach or exceed 95°F: observation/buddy system, mandatory cool-down rests of 10 minutes net every 2 hours, pre-shift meeting on high-heat procedures, and designated employee to call emergency services.",
      requiredReferences: ["8 CCR 3395(e)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "4. Emergency Response Procedures",
      purpose: "How to respond to signs/symptoms of heat illness. Must include procedures for contacting emergency services, ensuring clear directions to the worksite, and transporting affected employees.",
      requiredReferences: ["8 CCR 3395(f)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Acclimatization",
      purpose: "Procedures for new employees and employees returning from absence of 10+ days. Close observation during the first 14 days of employment.",
      requiredReferences: ["8 CCR 3395(g)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Training",
      purpose: "Training for all employees AND supervisors on heat illness signs/symptoms, risk factors, prevention, emergency procedures, and this plan's contents. Supervisor training must include monitoring for symptoms and response procedures.",
      requiredReferences: ["8 CCR 3395(h)", "8 CCR 3395(i)"],
      targetWords: 300,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Transportation-Specific Templates
// ---------------------------------------------------------------------------

const FLEET_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "fleet-safety-program",
  title: "Fleet Safety Program",
  vertical: "transportation",
  description: "Comprehensive fleet safety and driver compliance program covering Cal/OSHA and DOT requirements.",
  jurisdiction: "multi",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This program covers Cal/OSHA workplace safety requirements. DOT/FMCSA compliance is referenced but may require additional carrier-specific documentation.",
  sections: [
    {
      heading: "1. Driver Qualification and CDL Compliance",
      purpose: "Describe driver qualification file requirements: CDL verification, medical certificate tracking, MVR review, road test documentation, employment verification.",
      requiredReferences: ["49 CFR Part 391", "8 CCR 3203"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Vehicle Inspection and Maintenance",
      purpose: "Describe pre-trip and post-trip inspection procedures, preventive maintenance schedules, and out-of-service criteria.",
      requiredReferences: ["49 CFR Part 396", "8 CCR 3203(a)(4)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "3. Accident/Incident Reporting",
      purpose: "Describe procedures for reporting vehicle accidents and workplace injuries. Must cover both DOT-recordable accidents and Cal/OSHA reportable incidents.",
      requiredReferences: ["49 CFR 390.15", "8 CCR 3203(a)(5)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "4. Drug and Alcohol Testing Program",
      purpose: "Describe DOT-mandated drug and alcohol testing: pre-employment, random, post-accident, reasonable suspicion, return-to-duty, and follow-up.",
      requiredReferences: ["49 CFR Part 382"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Hours of Service Compliance",
      purpose: "Describe HOS recordkeeping, ELD requirements, and fatigue management procedures.",
      requiredReferences: ["49 CFR Part 395"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Hazardous Materials Transport",
      purpose: "If applicable: describe hazmat transport documentation, driver training, shipping papers, placarding, and emergency response procedures.",
      requiredReferences: ["49 CFR Parts 171-180"],
      targetWords: 250,
      alwaysInclude: false,
    },
  ],
}

// ---------------------------------------------------------------------------
// Warehouse/Wholesale-Specific Templates
// ---------------------------------------------------------------------------

const PIT_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "pit-safety-program",
  title: "Powered Industrial Truck (Forklift) Safety Program",
  vertical: "wholesale",
  description: "Forklift operator training and safety program. #1 Cal/OSHA citation for warehouses.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Each forklift operator must complete the full training program including classroom, practical, and workplace evaluation before operating any powered industrial truck.",
  sections: [
    {
      heading: "1. Operator Training Program",
      purpose: "Describe the three-part training: classroom/online instruction, practical exercises, and workplace performance evaluation by a qualified trainer.",
      requiredReferences: ["8 CCR 3668(b)", "8 CCR 3668(c)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "2. Operator Evaluation and Certification",
      purpose: "Describe how operators are evaluated and certified. Must include evaluation criteria, who conducts evaluations, and certification documentation.",
      requiredReferences: ["8 CCR 3668(d)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. Refresher Training Triggers",
      purpose: "Describe when refresher training is required: observed unsafe operation, near-miss or accident, new equipment type, workplace condition changes, and 3-year evaluation cycle.",
      requiredReferences: ["8 CCR 3668(e)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "4. Pre-Shift Inspection Procedures",
      purpose: "Describe daily pre-shift inspection checklist: brakes, steering, controls, warning devices, tires, forks, hydraulics, and battery/fuel.",
      requiredReferences: ["8 CCR 3664(a)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Operating Rules and Pedestrian Safety",
      purpose: "Describe operating rules: speed limits, aisle clearance, load capacity, pedestrian zones, and prohibited practices.",
      requiredReferences: ["8 CCR 3668(a)", "8 CCR 3650"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "6. Maintenance and Out-of-Service Procedures",
      purpose: "Describe maintenance schedules, out-of-service tagging procedures, and who is authorized to perform repairs.",
      requiredReferences: ["8 CCR 3668(f)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Retail-Specific Templates
// ---------------------------------------------------------------------------

const RETAIL_STORE_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "store-safety-program",
  title: "Multi-Location Store Safety Program",
  vertical: "retail",
  description: "Consolidated safety program for multi-location retail operations. Covers fire safety, ergonomics, hazard communication, and per-location compliance tracking.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Each store location must maintain a site-specific version of this program. Protekon generates per-location documentation from the master program. This document must be reviewed when new locations open or existing locations change layout.",
  sections: [
    {
      heading: "1. Multi-Location Compliance Overview",
      purpose: "Establish the compliance framework for all store locations. Each location requires its own site-specific IIPP and WVPP. This section defines how the master program cascades to individual locations, including the responsible person at each site and how locations are added/removed.",
      requiredReferences: ["8 CCR 3203(a)(1)", "Labor Code §6401.9"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Fire Safety and Emergency Evacuation",
      purpose: "Describe fire safety requirements for retail spaces: exit signage, aisle clearance, fire extinguisher placement and inspection schedule, emergency evacuation routes per location, and employee assembly points. Must address seasonal changes (holiday displays blocking exits, temporary fixtures).",
      requiredReferences: ["8 CCR 3220", "Title 19 CCR", "8 CCR 3221"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "3. Ergonomic Hazard Assessment",
      purpose: "Identify ergonomic risks specific to retail: repetitive stocking/shelving, prolonged standing, manual lifting of merchandise, register operation posture. Describe assessment procedures, risk scoring, and corrective measures (anti-fatigue mats, lift-assist equipment, rotation schedules).",
      requiredReferences: ["8 CCR 5110"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "4. Hazard Communication Program",
      purpose: "Describe the hazard communication program for cleaning chemicals, pest control products, and any other hazardous substances used in retail operations. Must include SDS access locations, container labeling, and employee training on chemical hazards.",
      requiredReferences: ["8 CCR 5194", "8 CCR 5194(b)", "8 CCR 5194(h)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Slip, Trip, and Fall Prevention",
      purpose: "Describe prevention measures for the #1 retail workplace injury: wet floor procedures, floor condition inspections, lighting requirements, stockroom organization standards, ladder safety for reaching high shelves, and seasonal hazard management (rain tracking, ice).",
      requiredReferences: ["8 CCR 3203(a)(4)", "8 CCR 3231"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "6. Customer Interaction and Workplace Violence Prevention",
      purpose: "Address retail-specific workplace violence risks: customer confrontations (Type 2), robbery prevention (Type 1), cash handling procedures, de-escalation training, lone worker policies for opening/closing, and security measures. Cross-references the WVPP but provides retail-specific protocols.",
      requiredReferences: ["Labor Code §6401.9", "8 CCR 3203(a)(6)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "7. Seasonal and Temporary Worker Safety",
      purpose: "Describe procedures for onboarding seasonal/temporary workers during peak periods (holiday, back-to-school). Must include abbreviated safety orientation requirements, supervision ratios, task restrictions for untrained workers, and documentation requirements.",
      requiredReferences: ["8 CCR 3203(a)(7)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "8. Per-Location Compliance Tracking",
      purpose: "Describe how compliance status is tracked across all locations: inspection schedules, training completion by location, incident reporting aggregation, and escalation procedures when a location falls out of compliance. Include the schedule for location-level audits.",
      requiredReferences: ["8 CCR 3203(b)"],
      targetWords: 250,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Hospitality-Specific Templates
// ---------------------------------------------------------------------------

const HOSPITALITY_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "hospitality-safety-program",
  title: "Guest and Employee Safety Program",
  vertical: "hospitality",
  description: "Comprehensive safety program for hotels, restaurants, and event venues. Covers bloodborne pathogen exposure, food safety compliance, chemical management, and guest/employee incident response.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This program covers Cal/OSHA workplace safety requirements. Health department food safety requirements (CalCode) are referenced but may require additional facility-specific documentation. Properties with pools, spas, or fitness centers must add supplemental safety procedures.",
  sections: [
    {
      heading: "1. Bloodborne Pathogen Exposure Control",
      purpose: "Hospitality workers encounter blood/OPIM through guest room cleaning (used sharps, bodily fluids), first aid response, and laundry handling. Describe exposure determination (which job classifications have exposure), universal precautions, PPE requirements (gloves for housekeeping, face protection for laundry), sharps disposal procedures, and the Hepatitis B vaccination program.",
      requiredReferences: ["8 CCR 5193(c)(2)", "8 CCR 5193(d)", "8 CCR 5193(f)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "2. Chemical Hazard Management",
      purpose: "Describe chemical management for hospitality: industrial cleaning products, pool/spa chemicals (if applicable), kitchen degreasers, laundry chemicals, pest control. Must include SDS access, container labeling, chemical storage separation, and spill response. Address the risk of mixing incompatible cleaning products.",
      requiredReferences: ["8 CCR 5194", "8 CCR 5194(h)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "3. Kitchen and Food Service Safety",
      purpose: "Describe kitchen-specific safety: burn prevention, knife safety, wet floor management, walk-in freezer safety (entrapment prevention), deep fryer operation, and ventilation hood maintenance. Cross-reference CalCode food safety requirements but focus on the Cal/OSHA workplace safety elements.",
      requiredReferences: ["8 CCR 3203(a)(4)", "Health & Safety Code §113700+"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "4. Slip, Trip, and Fall Prevention",
      purpose: "Address the #1 hospitality workplace injury: wet floor management in lobbies/restrooms/kitchens, lighting in corridors and stairwells, exterior walkway maintenance, pool deck safety (if applicable), and housekeeping cart placement in corridors.",
      requiredReferences: ["8 CCR 3203(a)(4)", "8 CCR 3231"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Guest-Involved Incident Response",
      purpose: "Describe procedures when incidents involve guests: medical emergencies on property, guest-on-employee confrontations (Type 2 workplace violence), domestic disturbances in guest rooms (Type 4), intoxicated guests, and trespassing (Type 1). Must cover when to call 911, how to document for both the WVPP incident log and property incident records, and liability preservation.",
      requiredReferences: ["Labor Code §6401.9", "8 CCR 3203(a)(5)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "6. Ergonomics and Physical Demands",
      purpose: "Address ergonomic risks specific to hospitality: housekeeping (repetitive bending, pushing heavy carts, making beds), laundry (lifting, sorting), front desk (prolonged standing), banquet setup (table/chair moving). Include assessment procedures and corrective measures.",
      requiredReferences: ["8 CCR 5110"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Heat Illness Prevention",
      purpose: "If the property has outdoor workers (valet, grounds maintenance, pool staff, outdoor event workers): describe the heat illness prevention program including water provision, shade access, high-heat procedures (95°F+), acclimatization for new workers, and emergency response. If no outdoor workers, state the exemption and monitoring procedure for when outdoor tasks arise.",
      requiredReferences: ["8 CCR 3395"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "8. Training Matrix by Role",
      purpose: "Define training requirements by job role: housekeeping (BBP, chemical, ergonomics), kitchen (burn prevention, knife, wet floor), front desk (emergency response, de-escalation, guest incidents), maintenance (LOTO if applicable, electrical, confined space if applicable), management (incident investigation, regulatory reporting). Include frequencies and documentation requirements.",
      requiredReferences: ["8 CCR 3203(a)(7)", "8 CCR 5193(g)(2)"],
      targetWords: 350,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Real Estate / Property Management-Specific Templates
// ---------------------------------------------------------------------------

const PROPERTY_COMPLIANCE_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "property-compliance-program",
  title: "Property Portfolio Compliance Program",
  vertical: "real-estate",
  description: "Compliance program for property management companies covering habitability standards, lead-based paint disclosures, tenant safety, and municipal ordinance tracking across a multi-property portfolio.",
  jurisdiction: "multi",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "semi-annual",
  retentionYears: 7,
  disclaimer: "This program covers workplace safety for property management employees AND regulatory compliance obligations for managed properties. Tenant-facing obligations vary by municipality — Protekon tracks city-by-city ordinance requirements for properties in the portfolio. This document must be updated when properties are added or removed from the portfolio.",
  sections: [
    {
      heading: "1. Portfolio Compliance Overview",
      purpose: "Map the compliance landscape for the property portfolio: list all managed properties with addresses, unit counts, property types (residential/commercial/mixed), and the municipalities they fall under. Identify which properties trigger which regulatory requirements based on age (pre-1978 for lead paint), size, and location.",
      requiredReferences: ["Civil Code §1940-1954.06", "Health & Safety Code §17920.3"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "2. Habitability Standards and Inspection Schedule",
      purpose: "Describe the California habitability standards that apply to residential properties: weatherproofing, plumbing, heating, electrical, sanitation, structural integrity, and building/housing code compliance. Define the inspection schedule for each property, including pre-tenancy, annual, and complaint-triggered inspections. Reference Green v. Superior Court (1974) standard.",
      requiredReferences: ["Civil Code §1941", "Civil Code §1941.1", "Health & Safety Code §17920.3"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "3. Lead-Based Paint Disclosure and Management",
      purpose: "For properties built before 1978: describe the lead-based paint disclosure requirements, EPA RRP Rule compliance for renovation work, lead hazard evaluation procedures, and tenant notification requirements. Include the disclosure form process and record retention requirements.",
      requiredReferences: ["42 USC §4852d", "Civil Code §1102.6", "40 CFR Part 745"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "4. Mold and Environmental Hazard Protocols",
      purpose: "Describe procedures for mold identification, remediation, and tenant notification. Include asbestos management for pre-1980 buildings, radon testing requirements (if applicable), and documentation of environmental assessments. Cover the landlord's duty to disclose known environmental hazards under California law.",
      requiredReferences: ["Health & Safety Code §26147-26148", "Civil Code §1102"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Tenant Safety Systems",
      purpose: "Describe required safety installations: smoke detectors (per unit and common areas), carbon monoxide detectors, fire extinguishers in common areas, exterior lighting, and security measures. Include inspection and testing schedules, battery replacement schedule, and documentation of compliance.",
      requiredReferences: ["Health & Safety Code §13113.8", "Health & Safety Code §17926", "Health & Safety Code §13260"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "6. Municipal Ordinance Tracking",
      purpose: "Identify the specific municipalities where portfolio properties are located and the local ordinances that apply beyond state law: rent control/stabilization (if applicable), just-cause eviction protections, local inspection programs, business license requirements for rental properties, and any city-specific habitability standards that exceed state minimums. Describe how Protekon monitors city council actions affecting the portfolio.",
      requiredReferences: ["Civil Code §1946.2", "Civil Code §1947.12"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "7. Vendor and Contractor Compliance",
      purpose: "Describe requirements for vendors performing work on managed properties: contractor licensing verification (CSLB for construction work), insurance requirements (general liability, workers' comp), lead-safe work practices certification for pre-1978 properties, and documentation retained per vendor engagement.",
      requiredReferences: ["Business & Professions Code §7000+", "40 CFR Part 745.85"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "8. Employee Workplace Safety (Property Management Staff)",
      purpose: "Cover Cal/OSHA requirements for property management employees who perform maintenance, inspections, or showing activities: lone worker safety for property visits, vehicle safety for multi-property travel, slip/trip/fall prevention during property inspections, and confined space awareness for utility areas. Cross-references the IIPP.",
      requiredReferences: ["8 CCR 3203", "Labor Code §6401.9"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "9. Incident Documentation and Liability Protection",
      purpose: "Describe how property-related incidents are documented: tenant complaints, maintenance emergencies, injury on property (tenant or visitor), and code enforcement actions. Include documentation standards that protect the management company's liability position, response time requirements, and how incident records are retained.",
      requiredReferences: ["Civil Code §1942", "8 CCR 3203(a)(5)"],
      targetWords: 300,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Template Registry
// ---------------------------------------------------------------------------

/** All document templates organized by vertical → document type */
const TEMPLATE_REGISTRY: Record<string, DocumentTemplate[]> = {
  // Cross-vertical (every client gets these)
  all: [
    WVPP_TEMPLATE,
    IIPP_TEMPLATE,
    EMERGENCY_ACTION_PLAN_TEMPLATE,
  ],
  // Vertical-specific
  construction: [FALL_PROTECTION_PLAN_TEMPLATE],
  healthcare: [BBP_EXPOSURE_CONTROL_PLAN_TEMPLATE],
  manufacturing: [LOTO_PROGRAM_TEMPLATE],
  agriculture: [HEAT_ILLNESS_PREVENTION_PLAN_TEMPLATE],
  transportation: [FLEET_SAFETY_PROGRAM_TEMPLATE],
  wholesale: [PIT_SAFETY_PROGRAM_TEMPLATE],
  retail: [RETAIL_STORE_SAFETY_PROGRAM_TEMPLATE],
  hospitality: [HOSPITALITY_SAFETY_PROGRAM_TEMPLATE],
  "real-estate": [PROPERTY_COMPLIANCE_PROGRAM_TEMPLATE],
  // Auto services: use cross-vertical templates only until vertical is fully built.
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Get a specific document template by vertical and document type ID.
 * Checks vertical-specific templates first, then cross-vertical.
 */
export function getDocumentTemplate(
  vertical: string,
  documentTypeId: string
): DocumentTemplate | null {
  // Check vertical-specific first
  const verticalTemplates = TEMPLATE_REGISTRY[vertical] ?? []
  const found = verticalTemplates.find((t) => t.id === documentTypeId)
  if (found) return found

  // Fall back to cross-vertical
  const crossVertical = TEMPLATE_REGISTRY.all ?? []
  return crossVertical.find((t) => t.id === documentTypeId) ?? null
}

/**
 * Get all available document templates for a given vertical.
 * Returns cross-vertical templates + vertical-specific templates.
 */
export function getTemplatesForVertical(vertical: string): DocumentTemplate[] {
  const cross = TEMPLATE_REGISTRY.all ?? []
  const specific = TEMPLATE_REGISTRY[vertical] ?? []
  return [...cross, ...specific]
}

/**
 * Get all document type IDs available for a vertical.
 * Used by the document request UI to show available document types.
 */
export function getAvailableDocumentTypes(
  vertical: string
): { id: string; title: string; description: string }[] {
  return getTemplatesForVertical(vertical).map((t) => ({
    id: t.id,
    title: t.title,
    description: t.description,
  }))
}

/**
 * Validate that required client fields are present for a document type.
 * Call before invoking the AI generator.
 */
export function validateClientData(
  template: DocumentTemplate,
  clientData: Record<string, unknown>
): { valid: boolean; missing: string[] } {
  const missing = template.requiredClientFields.filter(
    (field) => !clientData[field]
  )
  return { valid: missing.length === 0, missing }
}

/**
 * Build the AI prompt section structure from a template.
 * This is what gets injected into the AI generator prompt so Claude
 * fills in content within the locked structure.
 */
export function buildSectionPrompt(template: DocumentTemplate): string {
  const lines = template.sections
    .filter((s) => s.alwaysInclude)
    .map(
      (s) =>
        `### ${s.heading}\nPurpose: ${s.purpose}\nRequired regulatory references: ${s.requiredReferences.join(", ")}\nTarget length: ~${s.targetWords} words`
    )

  return `Document: ${template.title}
Jurisdiction: ${template.jurisdiction === "cal-osha" ? "Cal/OSHA (California)" : template.jurisdiction === "federal-osha" ? "Federal OSHA" : template.jurisdiction === "multi" ? "Cal/OSHA + Federal" : template.jurisdiction.toUpperCase()}

Generate content for EACH of the following sections. Do NOT add, remove, or rename any sections. Fill in the body for each section using the purpose and required references as your guide.

${lines.join("\n\n")}

Output format: Return a JSON object with this structure:
{
  "title": "${template.title}",
  "sections": [
    { "heading": "exact heading from above", "body": "your generated content" }
  ],
  "recommendations": ["3-5 specific actionable recommendations based on the client's gaps"]
}

Rules:
- Every required regulatory reference MUST appear in the relevant section body
- Content must be site-specific using the business name, location, and employee count provided
- Do NOT add sections beyond those listed above
- Do NOT rename section headings
- Each section body should be approximately the target word count
- All regulatory references must be California-specific (Cal/OSHA Title 8 CCR, Labor Code)`
}
