/**
 * Document Template Registry
 *
 * Defines the exact structure, required sections, and regulatory references
 * for every document type across all 10 Protekon verticals.
 *
 * The AI generator fills in the CONTENT. The template locks the STRUCTURE.
 * This guarantees consistent outputs regardless of how many times a document
 * is generated — same sections, same order, same regulatory references.
 *
 * Usage:
 *   const template = getDocumentTemplate("construction", "wvpp")
 *   // Pass template.sections to the AI as required output structure
 *   // AI fills in section.body for each section
 *   // PDF renderer uses template.sections in order
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SectionTemplate = {
  /** Section heading — rendered as-is in the PDF. AI does NOT rename this. */
  heading: string
  /** What this section must cover — injected into the AI prompt as instructions. */
  purpose: string
  /** Specific regulatory references that MUST appear in this section's content. */
  requiredReferences: string[]
  /** Estimated word count for the AI to target. */
  targetWords: number
  /** If true, this section is included even when no gap exists for it. */
  alwaysInclude: boolean
}

export type DocumentTemplate = {
  /** Machine-readable document type ID. Stored in documents.type column. */
  id: string
  /** Human-readable title rendered in PDF header. */
  title: string
  /** Which vertical this template belongs to. "all" = cross-vertical. */
  vertical: string
  /** Document description for the knowledge base / UI. */
  description: string
  /** Primary regulatory authority for this document. */
  jurisdiction: "cal-osha" | "federal-osha" | "hipaa" | "dot" | "cslb" | "dpr" | "multi"
  /** Required client data fields — generator will error if these are missing. */
  requiredClientFields: string[]
  /** Ordered section templates — the AI fills content within this structure. */
  sections: SectionTemplate[]
  /** Footer disclaimer text for the PDF. */
  disclaimer: string
  /** How often this document should be refreshed. */
  refreshCycle: "annual" | "semi-annual" | "quarterly" | "on-change" | "one-time"
  /** Minimum retention period in years. */
  retentionYears: number
}

// ---------------------------------------------------------------------------
// Cross-Vertical Templates (apply to all verticals)
// ---------------------------------------------------------------------------

const WVPP_TEMPLATE: DocumentTemplate = {
  id: "wvpp",
  title: "Workplace Violence Prevention Plan",
  vertical: "all",
  description: "Site-specific WVPP required by California SB 553 (Labor Code §6401.9). Applies to all employers with 10+ employees.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This plan was generated by Protekon based on the client's intake data and Cal/OSHA Model WVPP framework. It must be reviewed by the responsible person identified in Section 1 and updated whenever site conditions or personnel change.",
  sections: [
    {
      heading: "1. Responsible Persons",
      purpose: "Identify the person(s) responsible for implementing the WVPP. Must include name/title of the person with authority and responsibility for the plan.",
      requiredReferences: ["Labor Code §6401.9(b)(1)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "2. Employee Involvement",
      purpose: "Describe how employees are involved in developing, implementing, and reviewing the WVPP. Must include the mechanism for employee input (e.g., safety committee, anonymous reporting, direct feedback).",
      requiredReferences: ["Labor Code §6401.9(b)(2)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. Workplace Violence Hazard Identification and Evaluation",
      purpose: "Describe how workplace violence hazards are identified and evaluated. Must include initial assessment results, environmental risk factors (lighting, layout, public access), and staffing-related risk factors.",
      requiredReferences: ["Labor Code §6401.9(b)(3)", "8 CCR 3203(a)(4)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "4. Hazard Correction",
      purpose: "Describe procedures to correct identified hazards in a timely manner. Must include both immediate interim measures and long-term corrective actions.",
      requiredReferences: ["Labor Code §6401.9(b)(4)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Incident Response Procedures",
      purpose: "Describe how the employer responds to actual or potential workplace violence emergencies. Must include communication protocols, evacuation procedures, law enforcement contact procedures, and medical response.",
      requiredReferences: ["Labor Code §6401.9(b)(5)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "6. Post-Incident Response and Investigation",
      purpose: "Describe procedures for post-incident response, including investigation procedures, support for affected employees, and corrective action identification.",
      requiredReferences: ["Labor Code §6401.9(b)(6)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Training Requirements",
      purpose: "Describe the training program including initial training for new employees, annual refresher training, and additional training when the plan is updated. Training must be interactive and specific to this worksite.",
      requiredReferences: ["Labor Code §6401.9(b)(7)", "Labor Code §6401.9(e)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "8. Incident Log Procedures",
      purpose: "Describe how workplace violence incidents are logged, including the Violent Incident Log format, required data fields per §6401.9(d), PII protections, 5-year retention, and employee access rights (15 calendar days).",
      requiredReferences: ["Labor Code §6401.9(d)", "Labor Code §6401.9(d)(2)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "9. Plan Review and Updates",
      purpose: "Describe the schedule and triggers for reviewing and updating this plan. Must include annual review, post-incident review, and review when workplace conditions change.",
      requiredReferences: ["Labor Code §6401.9(b)(8)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

const IIPP_TEMPLATE: DocumentTemplate = {
  id: "iipp",
  title: "Injury and Illness Prevention Program",
  vertical: "all",
  description: "Site-specific IIPP required by Cal/OSHA (8 CCR §3203). Every California employer must maintain a written, site-specific IIPP.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This IIPP was generated by Protekon based on the client's worksite data and Cal/OSHA requirements under 8 CCR §3203. It must be reviewed annually and updated when conditions change.",
  sections: [
    {
      heading: "1. Responsible Person",
      purpose: "Identify the person with authority and responsibility for implementing the IIPP. Name and title required.",
      requiredReferences: ["8 CCR 3203(a)(1)"],
      targetWords: 150,
      alwaysInclude: true,
    },
    {
      heading: "2. Compliance System",
      purpose: "Describe how the employer ensures employee compliance with safe work practices. Must include recognition programs, disciplinary procedures, and supervisor accountability.",
      requiredReferences: ["8 CCR 3203(a)(2)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. Communication System",
      purpose: "Describe how safety information is communicated to employees. Must include the method (meetings, bulletin boards, written communications) and how employees can report hazards without fear of reprisal.",
      requiredReferences: ["8 CCR 3203(a)(3)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "4. Hazard Identification and Evaluation",
      purpose: "Describe procedures for identifying and evaluating workplace hazards. Must include initial assessment, periodic inspections, and assessment when new substances/processes/equipment are introduced.",
      requiredReferences: ["8 CCR 3203(a)(4)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "5. Hazard Correction",
      purpose: "Describe procedures for correcting identified hazards in a timely manner. Must include interim protective measures when a hazard cannot be immediately corrected.",
      requiredReferences: ["8 CCR 3203(a)(6)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "6. Accident/Exposure Investigation",
      purpose: "Describe procedures for investigating workplace accidents and exposures. Must include investigation procedures, root cause analysis, and corrective action documentation.",
      requiredReferences: ["8 CCR 3203(a)(5)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Training and Instruction",
      purpose: "Describe the employee training program. Must include training for new employees, training when new hazards are introduced, and training for supervisors. Must be specific to this worksite's hazards.",
      requiredReferences: ["8 CCR 3203(a)(7)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "8. Recordkeeping",
      purpose: "Describe how safety records are maintained including inspection records, training documentation, and hazard correction records.",
      requiredReferences: ["8 CCR 3203(b)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

const EMERGENCY_ACTION_PLAN_TEMPLATE: DocumentTemplate = {
  id: "eap",
  title: "Emergency Action Plan",
  vertical: "all",
  description: "Written emergency action plan required by Cal/OSHA (8 CCR §3220). Covers fire, earthquake, active threat, and medical emergencies.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This EAP was generated by Protekon. It must be reviewed with all employees upon initial assignment and whenever the plan changes.",
  sections: [
    {
      heading: "1. Emergency Escape Procedures and Routes",
      purpose: "Describe evacuation routes, assembly points, and exit assignments. Must be specific to the worksite layout.",
      requiredReferences: ["8 CCR 3220(a)(1)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Critical Operations Shutdown Procedures",
      purpose: "Identify employees assigned to shut down critical operations before evacuation and the procedures they follow.",
      requiredReferences: ["8 CCR 3220(a)(2)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "3. Employee Headcount Procedures",
      purpose: "Describe how employees are accounted for after evacuation.",
      requiredReferences: ["8 CCR 3220(a)(3)"],
      targetWords: 150,
      alwaysInclude: true,
    },
    {
      heading: "4. Rescue and Medical Duties",
      purpose: "Identify employees assigned to perform rescue or medical duties and their training requirements.",
      requiredReferences: ["8 CCR 3220(a)(4)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "5. Emergency Reporting Procedures",
      purpose: "Describe how emergencies are reported including fire, medical, active threat, and natural disaster.",
      requiredReferences: ["8 CCR 3220(a)(5)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Emergency Contact Information",
      purpose: "List emergency contacts including 911, local fire, local police, poison control, and internal emergency contacts.",
      requiredReferences: ["8 CCR 3220(a)(6)"],
      targetWords: 150,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Construction-Specific Templates
// ---------------------------------------------------------------------------

const FALL_PROTECTION_PLAN_TEMPLATE: DocumentTemplate = {
  id: "fall-protection-plan",
  title: "Fall Protection Plan",
  vertical: "construction",
  description: "Site-specific fall protection plan. #1 Cal/OSHA citation in construction.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "on-change",
  retentionYears: 5,
  disclaimer: "This fall protection plan must be reviewed whenever work conditions or locations change. A competent person must be designated to implement this plan on each jobsite.",
  sections: [
    {
      heading: "1. Fall Hazard Identification",
      purpose: "Identify all fall hazards at the worksite including open sides/edges, holes, leading edges, and elevated work surfaces above 7.5 feet.",
      requiredReferences: ["8 CCR 1509(a)", "8 CCR 1504"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Fall Protection Systems",
      purpose: "Describe the fall protection systems used — guardrails, safety nets, personal fall arrest systems. Must specify which system is used for each identified hazard.",
      requiredReferences: ["8 CCR 1509(b)", "8 CCR 1510"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "3. Competent Person Designation",
      purpose: "Identify the competent person responsible for fall protection on each jobsite. Must include qualifications.",
      requiredReferences: ["8 CCR 1509(a)"],
      targetWords: 150,
      alwaysInclude: true,
    },
    {
      heading: "4. Training Requirements",
      purpose: "Describe fall protection training including hazard recognition, equipment use, and rescue procedures.",
      requiredReferences: ["8 CCR 1509(d)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Rescue Procedures",
      purpose: "Describe how a worker in a fall arrest system will be rescued promptly. Must address self-rescue, assisted rescue, and suspension trauma.",
      requiredReferences: ["8 CCR 1511.1"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "6. Equipment Inspection and Maintenance",
      purpose: "Describe inspection schedules for fall protection equipment. Damaged equipment removal procedures.",
      requiredReferences: ["8 CCR 1509(c)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Healthcare-Specific Templates
// ---------------------------------------------------------------------------

const BBP_EXPOSURE_CONTROL_PLAN_TEMPLATE: DocumentTemplate = {
  id: "bbp-exposure-control",
  title: "Bloodborne Pathogen Exposure Control Plan",
  vertical: "healthcare",
  description: "Required exposure control plan for workplaces with occupational exposure to blood or other potentially infectious materials.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This Exposure Control Plan must be reviewed and updated annually, and whenever new tasks or procedures affect occupational exposure.",
  sections: [
    {
      heading: "1. Exposure Determination",
      purpose: "List all job classifications with occupational exposure to blood/OPIM. Include classifications where ALL employees have exposure and classifications where SOME employees have exposure (with task list).",
      requiredReferences: ["8 CCR 5193(c)(2)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Methods of Implementation and Control",
      purpose: "Describe universal precautions, engineering controls (sharps containers, needleless systems), work practice controls (hand washing, handling sharps), and PPE requirements.",
      requiredReferences: ["8 CCR 5193(d)(1)", "8 CCR 5193(d)(2)", "8 CCR 5193(d)(3)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "3. Hepatitis B Vaccination Program",
      purpose: "Describe the hepatitis B vaccination program offered to all employees with occupational exposure at no cost within 10 working days of assignment.",
      requiredReferences: ["8 CCR 5193(f)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "4. Post-Exposure Evaluation and Follow-Up",
      purpose: "Describe procedures following an exposure incident including documentation, medical evaluation, counseling, and source individual testing.",
      requiredReferences: ["8 CCR 5193(f)(3)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "5. Sharps Injury Log",
      purpose: "Describe the sharps injury log maintained for recording percutaneous injuries from contaminated sharps.",
      requiredReferences: ["8 CCR 5193(h)(5)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Training",
      purpose: "Describe initial and annual BBP training. Must include epidemiology, transmission modes, exposure control plan overview, recognition of exposure situations, and post-exposure procedures.",
      requiredReferences: ["8 CCR 5193(g)(2)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Recordkeeping",
      purpose: "Describe medical records (duration of employment + 30 years), training records (3 years), and sharps injury log retention.",
      requiredReferences: ["8 CCR 5193(h)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Manufacturing-Specific Templates
// ---------------------------------------------------------------------------

const LOTO_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "loto-program",
  title: "Lockout/Tagout (LOTO) Program",
  vertical: "manufacturing",
  description: "Energy control program for servicing and maintenance of machines and equipment where unexpected energization could cause injury.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Machine-specific LOTO procedures must be developed for each piece of equipment. This program establishes the overall framework. Equipment-specific procedures are generated separately.",
  sections: [
    {
      heading: "1. Purpose and Scope",
      purpose: "Define which machines, equipment, and energy sources are covered. Identify all energy types present (electrical, mechanical, hydraulic, pneumatic, chemical, thermal, gravitational).",
      requiredReferences: ["8 CCR 3314(a)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "2. Authorized and Affected Employees",
      purpose: "Define authorized employees (who perform LOTO), affected employees (who operate machines being locked out), and other employees (who work in the area). List by job title.",
      requiredReferences: ["8 CCR 3314(b)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "3. Lockout/Tagout Procedure — Step by Step",
      purpose: "The sequence: 1) Notify affected employees, 2) Shut down equipment, 3) Isolate energy sources, 4) Apply locks/tags, 5) Verify zero energy state, 6) Perform work, 7) Remove locks/tags, 8) Notify and restart.",
      requiredReferences: ["8 CCR 3314(c)", "8 CCR 3314(d)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "4. Lock and Tag Specifications",
      purpose: "Describe the locks and tags used. Must be durable, standardized, substantial enough to prevent removal without excessive force, and identify the authorized employee who applied them.",
      requiredReferences: ["8 CCR 3314(c)(5)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "5. Group Lockout/Tagout Procedures",
      purpose: "Procedures when multiple employees are servicing the same equipment. Must ensure each employee has individual lockout protection.",
      requiredReferences: ["8 CCR 3314(f)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Training and Certification",
      purpose: "Training requirements for authorized, affected, and other employees. Retraining triggers. Certification records.",
      requiredReferences: ["8 CCR 3314(g)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "7. Periodic Inspection",
      purpose: "Annual inspection of energy control procedures by an authorized employee who is NOT the one using the procedure being inspected.",
      requiredReferences: ["8 CCR 3314(e)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Agriculture-Specific Templates
// ---------------------------------------------------------------------------

const HEAT_ILLNESS_PREVENTION_PLAN_TEMPLATE: DocumentTemplate = {
  id: "heat-illness-prevention",
  title: "Heat Illness Prevention Plan",
  vertical: "agriculture",
  description: "Required heat illness prevention plan for outdoor workers. Cal/OSHA's most enforced agricultural standard.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This plan must be available at the worksite at all times. Supervisors and employees must be trained before beginning outdoor work.",
  sections: [
    {
      heading: "1. Water Provision",
      purpose: "Describe how fresh, pure, suitably cool drinking water is provided to employees free of charge. Must be located as close as practicable to work areas. Quantity: enough for each employee to drink 1 quart per hour.",
      requiredReferences: ["8 CCR 3395(c)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "2. Shade Access",
      purpose: "Describe shade structures available when temperatures exceed 80°F. Shade must be open to air or ventilated, located as close as practicable, and accommodate all employees on recovery or rest periods at the same time.",
      requiredReferences: ["8 CCR 3395(d)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. High-Heat Procedures (95°F+)",
      purpose: "Additional procedures when temperatures reach or exceed 95°F: observation/buddy system, mandatory cool-down rests of 10 minutes net every 2 hours, pre-shift meeting on high-heat procedures, and designated employee to call emergency services.",
      requiredReferences: ["8 CCR 3395(e)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "4. Emergency Response Procedures",
      purpose: "How to respond to signs/symptoms of heat illness. Must include procedures for contacting emergency services, ensuring clear directions to the worksite, and transporting affected employees.",
      requiredReferences: ["8 CCR 3395(f)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Acclimatization",
      purpose: "Procedures for new employees and employees returning from absence of 10+ days. Close observation during the first 14 days of employment.",
      requiredReferences: ["8 CCR 3395(g)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Training",
      purpose: "Training for all employees AND supervisors on heat illness signs/symptoms, risk factors, prevention, emergency procedures, and this plan's contents. Supervisor training must include monitoring for symptoms and response procedures.",
      requiredReferences: ["8 CCR 3395(h)", "8 CCR 3395(i)"],
      targetWords: 300,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Transportation-Specific Templates
// ---------------------------------------------------------------------------

const FLEET_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "fleet-safety-program",
  title: "Fleet Safety Program",
  vertical: "transportation",
  description: "Comprehensive fleet safety and driver compliance program covering Cal/OSHA and DOT requirements.",
  jurisdiction: "multi",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This program covers Cal/OSHA workplace safety requirements. DOT/FMCSA compliance is referenced but may require additional carrier-specific documentation.",
  sections: [
    {
      heading: "1. Driver Qualification and CDL Compliance",
      purpose: "Describe driver qualification file requirements: CDL verification, medical certificate tracking, MVR review, road test documentation, employment verification.",
      requiredReferences: ["49 CFR Part 391", "8 CCR 3203"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Vehicle Inspection and Maintenance",
      purpose: "Describe pre-trip and post-trip inspection procedures, preventive maintenance schedules, and out-of-service criteria.",
      requiredReferences: ["49 CFR Part 396", "8 CCR 3203(a)(4)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "3. Accident/Incident Reporting",
      purpose: "Describe procedures for reporting vehicle accidents and workplace injuries. Must cover both DOT-recordable accidents and Cal/OSHA reportable incidents.",
      requiredReferences: ["49 CFR 390.15", "8 CCR 3203(a)(5)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "4. Drug and Alcohol Testing Program",
      purpose: "Describe DOT-mandated drug and alcohol testing: pre-employment, random, post-accident, reasonable suspicion, return-to-duty, and follow-up.",
      requiredReferences: ["49 CFR Part 382"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Hours of Service Compliance",
      purpose: "Describe HOS recordkeeping, ELD requirements, and fatigue management procedures.",
      requiredReferences: ["49 CFR Part 395"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Hazardous Materials Transport",
      purpose: "If applicable: describe hazmat transport documentation, driver training, shipping papers, placarding, and emergency response procedures.",
      requiredReferences: ["49 CFR Parts 171-180"],
      targetWords: 250,
      alwaysInclude: false,
    },
  ],
}

// ---------------------------------------------------------------------------
// Warehouse/Wholesale-Specific Templates
// ---------------------------------------------------------------------------

const PIT_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "pit-safety-program",
  title: "Powered Industrial Truck (Forklift) Safety Program",
  vertical: "wholesale",
  description: "Forklift operator training and safety program. #1 Cal/OSHA citation for warehouses.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Each forklift operator must complete the full training program including classroom, practical, and workplace evaluation before operating any powered industrial truck.",
  sections: [
    {
      heading: "1. Operator Training Program",
      purpose: "Describe the three-part training: classroom/online instruction, practical exercises, and workplace performance evaluation by a qualified trainer.",
      requiredReferences: ["8 CCR 3668(b)", "8 CCR 3668(c)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "2. Operator Evaluation and Certification",
      purpose: "Describe how operators are evaluated and certified. Must include evaluation criteria, who conducts evaluations, and certification documentation.",
      requiredReferences: ["8 CCR 3668(d)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. Refresher Training Triggers",
      purpose: "Describe when refresher training is required: observed unsafe operation, near-miss or accident, new equipment type, workplace condition changes, and 3-year evaluation cycle.",
      requiredReferences: ["8 CCR 3668(e)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "4. Pre-Shift Inspection Procedures",
      purpose: "Describe daily pre-shift inspection checklist: brakes, steering, controls, warning devices, tires, forks, hydraulics, and battery/fuel.",
      requiredReferences: ["8 CCR 3664(a)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Operating Rules and Pedestrian Safety",
      purpose: "Describe operating rules: speed limits, aisle clearance, load capacity, pedestrian zones, and prohibited practices.",
      requiredReferences: ["8 CCR 3668(a)", "8 CCR 3650"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "6. Maintenance and Out-of-Service Procedures",
      purpose: "Describe maintenance schedules, out-of-service tagging procedures, and who is authorized to perform repairs.",
      requiredReferences: ["8 CCR 3668(f)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Retail-Specific Templates
// ---------------------------------------------------------------------------

const RETAIL_STORE_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "store-safety-program",
  title: "Multi-Location Store Safety Program",
  vertical: "retail",
  description: "Consolidated safety program for multi-location retail operations. Covers fire safety, ergonomics, hazard communication, and per-location compliance tracking.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Each store location must maintain a site-specific version of this program. Protekon generates per-location documentation from the master program. This document must be reviewed when new locations open or existing locations change layout.",
  sections: [
    {
      heading: "1. Multi-Location Compliance Overview",
      purpose: "Establish the compliance framework for all store locations. Each location requires its own site-specific IIPP and WVPP. This section defines how the master program cascades to individual locations, including the responsible person at each site and how locations are added/removed.",
      requiredReferences: ["8 CCR 3203(a)(1)", "Labor Code §6401.9"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "2. Fire Safety and Emergency Evacuation",
      purpose: "Describe fire safety requirements for retail spaces: exit signage, aisle clearance, fire extinguisher placement and inspection schedule, emergency evacuation routes per location, and employee assembly points. Must address seasonal changes (holiday displays blocking exits, temporary fixtures).",
      requiredReferences: ["8 CCR 3220", "Title 19 CCR", "8 CCR 3221"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "3. Ergonomic Hazard Assessment",
      purpose: "Identify ergonomic risks specific to retail: repetitive stocking/shelving, prolonged standing, manual lifting of merchandise, register operation posture. Describe assessment procedures, risk scoring, and corrective measures (anti-fatigue mats, lift-assist equipment, rotation schedules).",
      requiredReferences: ["8 CCR 5110"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "4. Hazard Communication Program",
      purpose: "Describe the hazard communication program for cleaning chemicals, pest control products, and any other hazardous substances used in retail operations. Must include SDS access locations, container labeling, and employee training on chemical hazards.",
      requiredReferences: ["8 CCR 5194", "8 CCR 5194(b)", "8 CCR 5194(h)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Slip, Trip, and Fall Prevention",
      purpose: "Describe prevention measures for the #1 retail workplace injury: wet floor procedures, floor condition inspections, lighting requirements, stockroom organization standards, ladder safety for reaching high shelves, and seasonal hazard management (rain tracking, ice).",
      requiredReferences: ["8 CCR 3203(a)(4)", "8 CCR 3231"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "6. Customer Interaction and Workplace Violence Prevention",
      purpose: "Address retail-specific workplace violence risks: customer confrontations (Type 2), robbery prevention (Type 1), cash handling procedures, de-escalation training, lone worker policies for opening/closing, and security measures. Cross-references the WVPP but provides retail-specific protocols.",
      requiredReferences: ["Labor Code §6401.9", "8 CCR 3203(a)(6)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "7. Seasonal and Temporary Worker Safety",
      purpose: "Describe procedures for onboarding seasonal/temporary workers during peak periods (holiday, back-to-school). Must include abbreviated safety orientation requirements, supervision ratios, task restrictions for untrained workers, and documentation requirements.",
      requiredReferences: ["8 CCR 3203(a)(7)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "8. Per-Location Compliance Tracking",
      purpose: "Describe how compliance status is tracked across all locations: inspection schedules, training completion by location, incident reporting aggregation, and escalation procedures when a location falls out of compliance. Include the schedule for location-level audits.",
      requiredReferences: ["8 CCR 3203(b)"],
      targetWords: 250,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Hospitality-Specific Templates
// ---------------------------------------------------------------------------

const HOSPITALITY_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "hospitality-safety-program",
  title: "Guest and Employee Safety Program",
  vertical: "hospitality",
  description: "Comprehensive safety program for hotels, restaurants, and event venues. Covers bloodborne pathogen exposure, food safety compliance, chemical management, and guest/employee incident response.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This program covers Cal/OSHA workplace safety requirements. Health department food safety requirements (CalCode) are referenced but may require additional facility-specific documentation. Properties with pools, spas, or fitness centers must add supplemental safety procedures.",
  sections: [
    {
      heading: "1. Bloodborne Pathogen Exposure Control",
      purpose: "Hospitality workers encounter blood/OPIM through guest room cleaning (used sharps, bodily fluids), first aid response, and laundry handling. Describe exposure determination (which job classifications have exposure), universal precautions, PPE requirements (gloves for housekeeping, face protection for laundry), sharps disposal procedures, and the Hepatitis B vaccination program.",
      requiredReferences: ["8 CCR 5193(c)(2)", "8 CCR 5193(d)", "8 CCR 5193(f)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "2. Chemical Hazard Management",
      purpose: "Describe chemical management for hospitality: industrial cleaning products, pool/spa chemicals (if applicable), kitchen degreasers, laundry chemicals, pest control. Must include SDS access, container labeling, chemical storage separation, and spill response. Address the risk of mixing incompatible cleaning products.",
      requiredReferences: ["8 CCR 5194", "8 CCR 5194(h)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "3. Kitchen and Food Service Safety",
      purpose: "Describe kitchen-specific safety: burn prevention, knife safety, wet floor management, walk-in freezer safety (entrapment prevention), deep fryer operation, and ventilation hood maintenance. Cross-reference CalCode food safety requirements but focus on the Cal/OSHA workplace safety elements.",
      requiredReferences: ["8 CCR 3203(a)(4)", "Health & Safety Code §113700+"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "4. Slip, Trip, and Fall Prevention",
      purpose: "Address the #1 hospitality workplace injury: wet floor management in lobbies/restrooms/kitchens, lighting in corridors and stairwells, exterior walkway maintenance, pool deck safety (if applicable), and housekeeping cart placement in corridors.",
      requiredReferences: ["8 CCR 3203(a)(4)", "8 CCR 3231"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Guest-Involved Incident Response",
      purpose: "Describe procedures when incidents involve guests: medical emergencies on property, guest-on-employee confrontations (Type 2 workplace violence), domestic disturbances in guest rooms (Type 4), intoxicated guests, and trespassing (Type 1). Must cover when to call 911, how to document for both the WVPP incident log and property incident records, and liability preservation.",
      requiredReferences: ["Labor Code §6401.9", "8 CCR 3203(a)(5)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "6. Ergonomics and Physical Demands",
      purpose: "Address ergonomic risks specific to hospitality: housekeeping (repetitive bending, pushing heavy carts, making beds), laundry (lifting, sorting), front desk (prolonged standing), banquet setup (table/chair moving). Include assessment procedures and corrective measures.",
      requiredReferences: ["8 CCR 5110"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "7. Heat Illness Prevention",
      purpose: "If the property has outdoor workers (valet, grounds maintenance, pool staff, outdoor event workers): describe the heat illness prevention program including water provision, shade access, high-heat procedures (95°F+), acclimatization for new workers, and emergency response. If no outdoor workers, state the exemption and monitoring procedure for when outdoor tasks arise.",
      requiredReferences: ["8 CCR 3395"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "8. Training Matrix by Role",
      purpose: "Define training requirements by job role: housekeeping (BBP, chemical, ergonomics), kitchen (burn prevention, knife, wet floor), front desk (emergency response, de-escalation, guest incidents), maintenance (LOTO if applicable, electrical, confined space if applicable), management (incident investigation, regulatory reporting). Include frequencies and documentation requirements.",
      requiredReferences: ["8 CCR 3203(a)(7)", "8 CCR 5193(g)(2)"],
      targetWords: 350,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Real Estate / Property Management-Specific Templates
// ---------------------------------------------------------------------------

const PROPERTY_COMPLIANCE_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "property-compliance-program",
  title: "Property Portfolio Compliance Program",
  vertical: "real-estate",
  description: "Compliance program for property management companies covering habitability standards, lead-based paint disclosures, tenant safety, and municipal ordinance tracking across a multi-property portfolio.",
  jurisdiction: "multi",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "semi-annual",
  retentionYears: 7,
  disclaimer: "This program covers workplace safety for property management employees AND regulatory compliance obligations for managed properties. Tenant-facing obligations vary by municipality — Protekon tracks city-by-city ordinance requirements for properties in the portfolio. This document must be updated when properties are added or removed from the portfolio.",
  sections: [
    {
      heading: "1. Portfolio Compliance Overview",
      purpose: "Map the compliance landscape for the property portfolio: list all managed properties with addresses, unit counts, property types (residential/commercial/mixed), and the municipalities they fall under. Identify which properties trigger which regulatory requirements based on age (pre-1978 for lead paint), size, and location.",
      requiredReferences: ["Civil Code §1940-1954.06", "Health & Safety Code §17920.3"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "2. Habitability Standards and Inspection Schedule",
      purpose: "Describe the California habitability standards that apply to residential properties: weatherproofing, plumbing, heating, electrical, sanitation, structural integrity, and building/housing code compliance. Define the inspection schedule for each property, including pre-tenancy, annual, and complaint-triggered inspections. Reference Green v. Superior Court (1974) standard.",
      requiredReferences: ["Civil Code §1941", "Civil Code §1941.1", "Health & Safety Code §17920.3"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "3. Lead-Based Paint Disclosure and Management",
      purpose: "For properties built before 1978: describe the lead-based paint disclosure requirements, EPA RRP Rule compliance for renovation work, lead hazard evaluation procedures, and tenant notification requirements. Include the disclosure form process and record retention requirements.",
      requiredReferences: ["42 USC §4852d", "Civil Code §1102.6", "40 CFR Part 745"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "4. Mold and Environmental Hazard Protocols",
      purpose: "Describe procedures for mold identification, remediation, and tenant notification. Include asbestos management for pre-1980 buildings, radon testing requirements (if applicable), and documentation of environmental assessments. Cover the landlord's duty to disclose known environmental hazards under California law.",
      requiredReferences: ["Health & Safety Code §26147-26148", "Civil Code §1102"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Tenant Safety Systems",
      purpose: "Describe required safety installations: smoke detectors (per unit and common areas), carbon monoxide detectors, fire extinguishers in common areas, exterior lighting, and security measures. Include inspection and testing schedules, battery replacement schedule, and documentation of compliance.",
      requiredReferences: ["Health & Safety Code §13113.8", "Health & Safety Code §17926", "Health & Safety Code §13260"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "6. Municipal Ordinance Tracking",
      purpose: "Identify the specific municipalities where portfolio properties are located and the local ordinances that apply beyond state law: rent control/stabilization (if applicable), just-cause eviction protections, local inspection programs, business license requirements for rental properties, and any city-specific habitability standards that exceed state minimums. Describe how Protekon monitors city council actions affecting the portfolio.",
      requiredReferences: ["Civil Code §1946.2", "Civil Code §1947.12"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "7. Vendor and Contractor Compliance",
      purpose: "Describe requirements for vendors performing work on managed properties: contractor licensing verification (CSLB for construction work), insurance requirements (general liability, workers' comp), lead-safe work practices certification for pre-1978 properties, and documentation retained per vendor engagement.",
      requiredReferences: ["Business & Professions Code §7000+", "40 CFR Part 745.85"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "8. Employee Workplace Safety (Property Management Staff)",
      purpose: "Cover Cal/OSHA requirements for property management employees who perform maintenance, inspections, or showing activities: lone worker safety for property visits, vehicle safety for multi-property travel, slip/trip/fall prevention during property inspections, and confined space awareness for utility areas. Cross-references the IIPP.",
      requiredReferences: ["8 CCR 3203", "Labor Code §6401.9"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "9. Incident Documentation and Liability Protection",
      purpose: "Describe how property-related incidents are documented: tenant complaints, maintenance emergencies, injury on property (tenant or visitor), and code enforcement actions. Include documentation standards that protect the management company's liability position, response time requirements, and how incident records are retained.",
      requiredReferences: ["Civil Code §1942", "8 CCR 3203(a)(5)"],
      targetWords: 300,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// MISSING TEMPLATES — prioritized by regulatory risk
// ---------------------------------------------------------------------------

// Construction: Silica Exposure Control Plan (HIGH PRIORITY — top penalty)
const SILICA_EXPOSURE_CONTROL_PLAN_TEMPLATE: DocumentTemplate = {
  id: "silica-exposure-control",
  title: "Respirable Crystalline Silica Exposure Control Plan",
  vertical: "construction",
  description: "Written exposure control plan for construction tasks disturbing silica (concrete cutting, grinding, drilling, jackhammering). Highest per-case penalties in construction.",
  jurisdiction: "federal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 30,
  disclaimer: "This plan must be updated whenever new silica-generating tasks are introduced. Medical surveillance records must be retained for 30 years.",
  sections: [
    { heading: "1. Scope and Application", purpose: "Identify all construction tasks generating respirable crystalline silica: concrete/masonry cutting, grinding, drilling, jackhammering, tuck-pointing, abrasive blasting. List each task and the employees exposed.", requiredReferences: ["29 CFR 1926.1153(a)", "29 CFR 1926.1153(c)"], targetWords: 300, alwaysInclude: true },
    { heading: "2. Table 1 Compliance or Alternative Exposure Assessment", purpose: "For each task, specify whether Table 1 specified exposure control methods are used OR objective air monitoring was conducted. Table 1 provides per-task controls (e.g., wet cutting with integrated water delivery for handheld power saws).", requiredReferences: ["29 CFR 1926.1153(c)(1)", "29 CFR 1926.1153(d)"], targetWords: 400, alwaysInclude: true },
    { heading: "3. Engineering and Work Practice Controls", purpose: "Describe specific engineering controls per task: water delivery systems, local exhaust ventilation, enclosed cabs with filtered air. Work practice controls: wet sweeping, HEPA vacuums, housekeeping.", requiredReferences: ["29 CFR 1926.1153(c)(1)", "29 CFR 1926.1153(f)(1)"], targetWords: 350, alwaysInclude: true },
    { heading: "4. Respiratory Protection Program", purpose: "When controls cannot reduce exposure below PEL (50 μg/m³ TWA): respirator selection per APF tables, annual fit testing, medical evaluation, proper use/maintenance.", requiredReferences: ["29 CFR 1926.1153(e)", "29 CFR 1910.134"], targetWords: 300, alwaysInclude: true },
    { heading: "5. Medical Surveillance", purpose: "For employees exposed above action level (25 μg/m³) for 30+ days/year: initial exam within 30 days, periodic exams every 3 years, chest X-ray and pulmonary function test. Written medical opinions within 30 days.", requiredReferences: ["29 CFR 1926.1153(h)"], targetWords: 300, alwaysInclude: true },
    { heading: "6. Competent Person Designation", purpose: "Identify the competent person at each worksite. Must be capable of identifying silica hazards and authorized to take corrective measures.", requiredReferences: ["29 CFR 1926.1153(g)"], targetWords: 200, alwaysInclude: true },
    { heading: "7. Training", purpose: "All exposed employees: health hazards of silica, methods to limit exposure, exposure monitoring and medical surveillance purpose/procedures, and this plan's contents.", requiredReferences: ["29 CFR 1926.1153(i)"], targetWords: 250, alwaysInclude: true },
    { heading: "8. Recordkeeping", purpose: "Exposure monitoring records: 30 years. Medical surveillance: employment duration + 30 years. Must be accessible to employees and OSHA.", requiredReferences: ["29 CFR 1926.1153(j)", "29 CFR 1910.1020"], targetWords: 200, alwaysInclude: true },
  ],
}

// Hearing Conservation Program (construction + manufacturing)
const HEARING_CONSERVATION_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "hearing-conservation",
  title: "Hearing Conservation Program",
  vertical: "all",
  description: "Required when employee noise exposure reaches or exceeds 85 dBA (8-hour TWA). Covers monitoring, audiometric testing, hearing protection, and training.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 30,
  disclaimer: "Audiometric testing must be administered by a qualified audiologist or technician under their supervision. Records retained for duration of employment.",
  sections: [
    { heading: "1. Noise Monitoring", purpose: "Initial baseline survey, area monitoring, personal dosimetry. Identify areas/tasks exceeding 85 dBA action level and 90 dBA PEL. Repeat when changes increase exposures.", requiredReferences: ["8 CCR 5097(a)", "29 CFR 1910.95(d)"], targetWords: 300, alwaysInclude: true },
    { heading: "2. Audiometric Testing Program", purpose: "Baseline audiogram within 6 months (1 year with mobile van). Annual audiograms. Standard Threshold Shift detection and follow-up.", requiredReferences: ["8 CCR 5097(b)", "29 CFR 1910.95(g)"], targetWords: 300, alwaysInclude: true },
    { heading: "3. Hearing Protection Devices", purpose: "Provided at no cost at 85 dBA+. Required at 90 dBA+. Types, NRR ratings, proper fit verification.", requiredReferences: ["8 CCR 5098", "29 CFR 1910.95(i)"], targetWords: 250, alwaysInclude: true },
    { heading: "4. Engineering and Administrative Controls", purpose: "Required at 90 dBA+: equipment maintenance, vibration dampening, sound barriers, rotation schedules.", requiredReferences: ["8 CCR 5096", "29 CFR 1910.95(b)(1)"], targetWords: 250, alwaysInclude: true },
    { heading: "5. Training", purpose: "Annual: effects of noise on hearing, audiometric testing purpose, proper HPD use/care, program contents.", requiredReferences: ["29 CFR 1910.95(k)"], targetWords: 250, alwaysInclude: true },
    { heading: "6. Recordkeeping", purpose: "Noise measurements: 2 years. Audiometric records: duration of employment. Include employee name, date, examiner, results.", requiredReferences: ["29 CFR 1910.95(m)", "8 CCR 5097(d)"], targetWords: 200, alwaysInclude: true },
  ],
}

// Healthcare: HIPAA Security Risk Analysis (HIGH PRIORITY — #1 OCR finding)
const HIPAA_SRA_TEMPLATE: DocumentTemplate = {
  id: "hipaa-sra",
  title: "HIPAA Security Risk Analysis",
  vertical: "healthcare",
  description: "#1 finding in OCR audits. Required annual assessment of threats and vulnerabilities to ePHI.",
  jurisdiction: "hipaa",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 6,
  disclaimer: "Must be conducted annually and whenever significant changes occur. Retain 6 years per 45 CFR §164.530(j).",
  sections: [
    { heading: "1. Scope of the Assessment", purpose: "Identify all electronic media and systems that create, receive, maintain, or transmit ePHI. Map data flows between systems.", requiredReferences: ["45 CFR §164.308(a)(1)(ii)(A)"], targetWords: 350, alwaysInclude: true },
    { heading: "2. Threat Identification", purpose: "Identify all reasonably anticipated threats: natural (fire, flood), human (hackers, social engineering), environmental (power failure, hardware malfunction).", requiredReferences: ["45 CFR §164.308(a)(1)(ii)(A)"], targetWords: 350, alwaysInclude: true },
    { heading: "3. Vulnerability Assessment", purpose: "For each system, assess vulnerabilities: missing patches, weak passwords, unencrypted data, insufficient logging, inadequate physical security.", requiredReferences: ["45 CFR §164.308(a)(1)(ii)(A)", "45 CFR §164.312"], targetWords: 350, alwaysInclude: true },
    { heading: "4. Current Security Measures", purpose: "Document existing safeguards: access controls, encryption, audit logging, backup, workforce training, physical security, BAAs.", requiredReferences: ["45 CFR §164.306(b)(1)"], targetWords: 300, alwaysInclude: true },
    { heading: "5. Risk Determination", purpose: "For each threat-vulnerability pair: rate likelihood (H/M/L) and impact (H/M/L). Assign overall risk level. Document methodology.", requiredReferences: ["45 CFR §164.308(a)(1)(ii)(A)"], targetWords: 300, alwaysInclude: true },
    { heading: "6. Risk Management Plan", purpose: "For each risk: mitigate, accept, transfer, or avoid. Include implementation timeline and responsible person.", requiredReferences: ["45 CFR §164.308(a)(1)(ii)(B)"], targetWords: 350, alwaysInclude: true },
    { heading: "7. Documentation and Review Schedule", purpose: "Retain 6 years. Annual review required. Additional reviews triggered by incidents, system changes, or organizational changes.", requiredReferences: ["45 CFR §164.316(b)(1)", "45 CFR §164.530(j)"], targetWords: 200, alwaysInclude: true },
  ],
}

// Healthcare: Aerosol Transmissible Disease Plan (Cal/OSHA specific)
const ATD_PLAN_TEMPLATE: DocumentTemplate = {
  id: "atd-plan",
  title: "Aerosol Transmissible Disease Exposure Control Plan",
  vertical: "healthcare",
  description: "Cal/OSHA-specific requirement beyond federal BBP. Written ATD plan addressing airborne transmission risks in healthcare facilities.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Must be reviewed annually and updated when new ATDs emerge or CDC/Cal/OSHA guidance changes.",
  sections: [
    { heading: "1. Exposure Determination", purpose: "Identify employees with occupational ATD exposure by job classification. Identify tasks and procedures that create exposure risk.", requiredReferences: ["8 CCR 5199(b)", "8 CCR 5199(d)(1)"], targetWords: 300, alwaysInclude: true },
    { heading: "2. Source Control Measures", purpose: "Triage screening, respiratory hygiene/cough etiquette, patient isolation (AIIR if available), visitor management.", requiredReferences: ["8 CCR 5199(d)(2)"], targetWords: 300, alwaysInclude: true },
    { heading: "3. Referral Procedures", purpose: "For facilities without AIIR: referral procedures, transport protocols, receiving facility communication.", requiredReferences: ["8 CCR 5199(d)(3)"], targetWords: 250, alwaysInclude: true },
    { heading: "4. Respiratory Protection Program", purpose: "N95 or higher selection, fit testing (annual), medical evaluation, seal checks, PAPR availability.", requiredReferences: ["8 CCR 5199(d)(4)", "8 CCR 5144"], targetWords: 300, alwaysInclude: true },
    { heading: "5. Employee Screening and Medical Services", purpose: "TB skin testing (initial/periodic), symptom monitoring, post-exposure management, positive conversion procedures.", requiredReferences: ["8 CCR 5199(g)"], targetWords: 300, alwaysInclude: true },
    { heading: "6. Training", purpose: "Annual: transmission modes, signs/symptoms, infection control, respiratory protection, reporting. Facility-specific ATDs.", requiredReferences: ["8 CCR 5199(h)"], targetWords: 250, alwaysInclude: true },
  ],
}

// Healthcare: BAA Tracker Template (document form)
const BAA_TRACKER_TEMPLATE: DocumentTemplate = {
  id: "baa-tracker",
  title: "Business Associate Agreement Compliance Tracker",
  vertical: "healthcare",
  description: "Structured BAA inventory tracking all vendors with PHI access, agreement status, renewal dates, and required provisions.",
  jurisdiction: "hipaa",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "semi-annual",
  retentionYears: 6,
  disclaimer: "BAAs must be retained for 6 years per HIPAA. Update when vendors are added, removed, or data relationships change.",
  sections: [
    { heading: "1. BAA Inventory", purpose: "All business associates: vendor name, service type, PHI types shared, execution date, expiration/renewal date, status.", requiredReferences: ["45 CFR §164.308(b)", "45 CFR §164.502(e)"], targetWords: 300, alwaysInclude: true },
    { heading: "2. Required BAA Provisions Checklist", purpose: "Verify: permitted uses/disclosures, safeguards obligation, breach notification (60 days), PHI return/destruction on termination, subcontractor chain-down, CE termination right.", requiredReferences: ["45 CFR §164.314(a)(2)", "45 CFR §164.504(e)(2)"], targetWords: 350, alwaysInclude: true },
    { heading: "3. Vendor Risk Assessment", purpose: "Per BA: PHI volume, access type, geographic location, BA security posture, breach history.", requiredReferences: ["45 CFR §164.308(a)(1)(ii)(A)"], targetWords: 300, alwaysInclude: true },
    { heading: "4. Monitoring and Renewal Schedule", purpose: "Renewal tracking (flag 90 days before expiration), annual BA compliance verification, breach response procedures, due diligence documentation.", requiredReferences: ["45 CFR §164.308(b)(3)"], targetWords: 250, alwaysInclude: true },
    { heading: "5. Termination and PHI Return/Destruction", purpose: "Written notice, PHI return/certified destruction timeline, verification, infeasibility procedures.", requiredReferences: ["45 CFR §164.504(e)(2)(ii)(I)"], targetWords: 250, alwaysInclude: true },
  ],
}

// Manufacturing: Machine Guarding Program
const MACHINE_GUARDING_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "machine-guarding",
  title: "Machine Guarding Program",
  vertical: "manufacturing",
  description: "Written machine guarding program covering point-of-operation guards, nip point protection, and rotating part enclosures per Cal/OSHA Title 8 §4001-4005.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Machine-specific guarding assessments must be conducted for each piece of equipment. Guards must never be removed or bypassed without LOTO procedures.",
  sections: [
    { heading: "1. Machine Inventory and Hazard Classification", purpose: "List all machines. For each, identify hazard type: point of operation, nip points, rotating parts, flying chips, reciprocating/transverse motion. Classify by risk.", requiredReferences: ["8 CCR 4001", "8 CCR 4002"], targetWords: 350, alwaysInclude: true },
    { heading: "2. Guard Types and Selection Criteria", purpose: "Fixed, interlocked, adjustable, self-adjusting guards, presence-sensing devices, two-hand tripping, restraint devices. Specify which guard for each machine.", requiredReferences: ["8 CCR 4003", "8 CCR 4004"], targetWords: 350, alwaysInclude: true },
    { heading: "3. Point-of-Operation Guarding", purpose: "Must prevent operator from reaching danger zone, not create additional hazards, allow safe maintenance, be firmly secured.", requiredReferences: ["8 CCR 4003(a)", "8 CCR 4005"], targetWords: 300, alwaysInclude: true },
    { heading: "4. Inspection and Maintenance Schedule", purpose: "Daily visual by operators, monthly documented by maintenance, annual comprehensive audit. Report/correct damaged or missing guards.", requiredReferences: ["8 CCR 4001", "8 CCR 3203(a)(4)"], targetWords: 300, alwaysInclude: true },
    { heading: "5. Guard Removal and Re-Installation Procedures", purpose: "Authorization process, LOTO cross-reference, reinstallation verification before production, authorized personnel list.", requiredReferences: ["8 CCR 3314", "8 CCR 4001"], targetWords: 250, alwaysInclude: true },
    { heading: "6. Training", purpose: "All employees near guarded machines: guard purpose/function, consequences of removal/bypass, deficiency reporting, maintenance request procedures.", requiredReferences: ["8 CCR 3203(a)(7)"], targetWords: 250, alwaysInclude: true },
  ],
}

// Manufacturing: Confined Space Entry Program
const CONFINED_SPACE_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "confined-space-program",
  title: "Permit-Required Confined Space Entry Program",
  vertical: "manufacturing",
  description: "Written program for permit-required confined space entry covering atmospheric monitoring, entry procedures, attendant duties, and rescue provisions.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Each permit-required confined space must be individually assessed. Entry permits retained at least 1 year. Review annually and after any incident.",
  sections: [
    { heading: "1. Confined Space Identification and Inventory", purpose: "Identify and label all confined spaces: tanks, vessels, silos, pits, vaults, tunnels, manholes. Classify as permit-required or non-permit based on atmospheric hazard, engulfment, configuration, other serious hazard.", requiredReferences: ["8 CCR 5157(c)", "8 CCR 5157(d)"], targetWords: 350, alwaysInclude: true },
    { heading: "2. Entry Permit System", purpose: "Written permit: space ID, purpose, date/time, authorized entrants, attendants, entry supervisor, hazards, atmospheric results, controls, communication. Valid for one entry period.", requiredReferences: ["8 CCR 5157(f)"], targetWords: 350, alwaysInclude: true },
    { heading: "3. Atmospheric Monitoring", purpose: "Test oxygen (19.5%-23.5%), flammable gases (<10% LEL), toxics (below PEL). Before entry and continuously during occupancy. Calibration schedule.", requiredReferences: ["8 CCR 5157(c)(5)", "8 CCR 5157(d)(5)"], targetWords: 300, alwaysInclude: true },
    { heading: "4. Entry Procedures and Attendant Duties", purpose: "Entrant duties (monitor, communicate, exit on alarm). Attendant duties (count, monitor, summon rescue, order evacuation — never enter). Entry supervisor duties (verify, authorize, terminate).", requiredReferences: ["8 CCR 5157(h)", "8 CCR 5157(i)", "8 CCR 5157(j)"], targetWords: 400, alwaysInclude: true },
    { heading: "5. Rescue and Emergency Provisions", purpose: "On-site team or documented emergency services agreement. Non-entry rescue preferred. Annual rescue practice. Retrieval systems for vertical entries >5 feet.", requiredReferences: ["8 CCR 5157(k)"], targetWords: 350, alwaysInclude: true },
    { heading: "6. Training and Certification", purpose: "Before first assignment and when duties change. Certification: employee name, trainer signature, date. Refresher when program changes or deficiencies found.", requiredReferences: ["8 CCR 5157(g)"], targetWords: 250, alwaysInclude: true },
  ],
}

// Agriculture: Wildfire Smoke Protection Plan
const WILDFIRE_SMOKE_PROTECTION_PLAN_TEMPLATE: DocumentTemplate = {
  id: "wildfire-smoke-protection",
  title: "Wildfire Smoke Protection Plan",
  vertical: "agriculture",
  description: "Required when AQI for PM2.5 reaches 151+. California's wildfire smoke standard is the most prescriptive in the nation.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Implement immediately when AQI for PM2.5 reaches 151. Monitor conditions throughout each work shift during wildfire season.",
  sections: [
    { heading: "1. AQI Monitoring Procedures", purpose: "Designate responsible person, monitoring sources (AirNow.gov, local AQMD, PurpleAir), check frequency (before shift + every 2 hours), worker notification method.", requiredReferences: ["8 CCR 5141.1(c)"], targetWords: 300, alwaysInclude: true },
    { heading: "2. Exposure Controls by AQI Level", purpose: "AQI 151-200: respirators for voluntary use, rest in filtered areas. AQI 201-300: require respirators, reduce exertion. AQI 301+: enclosed filtered-air structures, reduce exposure time.", requiredReferences: ["8 CCR 5141.1(d)", "8 CCR 5141.1(e)"], targetWords: 400, alwaysInclude: true },
    { heading: "3. Respiratory Protection", purpose: "When required (AQI 201+): N95+, proper fit (seal check each use), medical evaluation, sufficient supply.", requiredReferences: ["8 CCR 5141.1(e)", "8 CCR 5144"], targetWords: 300, alwaysInclude: true },
    { heading: "4. Training", purpose: "Before smoke season: health effects, AQI checking, plan procedures, respirator use, right to medical treatment without reprisal.", requiredReferences: ["8 CCR 5141.1(f)"], targetWords: 250, alwaysInclude: true },
    { heading: "5. Communication and Emergency Procedures", purpose: "AQI change notification, filtered-air shelter locations, symptom response procedures, emergency contacts.", requiredReferences: ["8 CCR 5141.1(d)", "8 CCR 3203(a)(3)"], targetWords: 250, alwaysInclude: true },
  ],
}

// Agriculture: Pesticide Safety Program
const PESTICIDE_SAFETY_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "pesticide-safety",
  title: "Pesticide Safety Training and Compliance Program",
  vertical: "agriculture",
  description: "Pesticide safety training, application recordkeeping, restricted material permits, and Worker Protection Standard compliance.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "Covers Cal/OSHA worker safety and DPR cross-references. Restricted material permits obtained separately from County Agricultural Commissioner.",
  sections: [
    { heading: "1. Pesticide Inventory and Use Records", purpose: "Complete inventory. Application records: product name, EPA registration, location, date/time, amount, applicator, REI. Retain 2 years.", requiredReferences: ["3 CCR §6624", "3 CCR §6626"], targetWords: 300, alwaysInclude: true },
    { heading: "2. Worker Protection Standard Compliance", purpose: "REIs, decontamination sites (water/soap/towels within 1/4 mile), treated area notification (posting or oral), early-entry protections.", requiredReferences: ["3 CCR §6764", "40 CFR Part 170"], targetWords: 350, alwaysInclude: true },
    { heading: "3. Pesticide Safety Training", purpose: "Before exposure and annually. In workers' language. Cover: safe handling, health effects, labels/SDSs, decontamination, emergency procedures.", requiredReferences: ["3 CCR §6724", "3 CCR §6764(b)"], targetWords: 300, alwaysInclude: true },
    { heading: "4. Personal Protective Equipment", purpose: "Per label: chemical-resistant gloves, coveralls, eye protection, respirators. Provided free, cleaned after use, stored separately.", requiredReferences: ["3 CCR §6738", "8 CCR 5194(d)"], targetWords: 250, alwaysInclude: true },
    { heading: "5. Restricted Material Permits", purpose: "If applicable: County Agricultural Commissioner permit process, use conditions, pre-application notification, recordkeeping.", requiredReferences: ["3 CCR §6400-6490"], targetWords: 200, alwaysInclude: false },
    { heading: "6. Emergency and Medical Response", purpose: "First aid, decontamination, medical access, poison control (1-800-222-1222), Cal/OSHA reporting for serious injuries.", requiredReferences: ["3 CCR §6726", "Labor Code §6409.1"], targetWords: 250, alwaysInclude: true },
  ],
}

// Auto Services: Spray Booth Compliance Program
const SPRAY_BOOTH_COMPLIANCE_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "spray-booth-compliance",
  title: "Spray Booth and Respiratory Protection Compliance Program",
  vertical: "auto-services",
  description: "Spray booth ventilation, isocyanate medical surveillance, hazmat storage, and fire prevention for automotive paint/refinishing.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 30,
  disclaimer: "Isocyanate medical surveillance records retained 30 years. Airflow measurements must be documented. Review when new coatings or equipment are introduced.",
  sections: [
    { heading: "1. Spray Booth Ventilation Requirements", purpose: "Adequate velocity to prevent flammable vapor accumulation, exhaust maintenance, filter replacement schedule, annual airflow measurement documentation, make-up air.", requiredReferences: ["8 CCR 5154", "29 CFR 1910.94(c)"], targetWords: 350, alwaysInclude: true },
    { heading: "2. Isocyanate Exposure Control", purpose: "For HDI/MDI/TDI exposure: monitoring, engineering controls (booth airflow), respiratory protection (supplied-air or PAPR w/ OV cartridges), medical surveillance.", requiredReferences: ["8 CCR 5155", "8 CCR 5208"], targetWords: 350, alwaysInclude: true },
    { heading: "3. Medical Surveillance (Isocyanate Exposure)", purpose: "Pre-assignment and periodic exams. Pulmonary function (FVC, FEV1), respiratory questionnaire, written opinions. Records: 30 years.", requiredReferences: ["8 CCR 5208(l)", "8 CCR 5155"], targetWords: 300, alwaysInclude: true },
    { heading: "4. Hazmat Storage and Waste Management", purpose: "Flammable liquid cabinets, chemical separation, used oil labeling (H&S Code §25250), waste manifesting.", requiredReferences: ["29 CFR 1910.106", "Health & Safety Code §25250"], targetWords: 300, alwaysInclude: true },
    { heading: "5. Fire Prevention for Paint Operations", purpose: "No-spark tools, extinguisher placement (within 10ft of booth), Class I Division 1/2 electrical ratings, hot work permits near paint storage.", requiredReferences: ["29 CFR 1910.107", "8 CCR 5154(h)"], targetWords: 300, alwaysInclude: true },
    { heading: "6. Training", purpose: "Booth operation/maintenance, isocyanate hazards, respirator use, hazmat handling, fire prevention, emergency procedures. Documented with dates/topics.", requiredReferences: ["8 CCR 5194(h)", "8 CCR 3203(a)(7)"], targetWords: 250, alwaysInclude: true },
  ],
}

// ---------------------------------------------------------------------------
// Template Registry
// ---------------------------------------------------------------------------
// Platform-Wide Templates (completing the 8 promised)
// ---------------------------------------------------------------------------

const HAZCOM_PROGRAM_TEMPLATE: DocumentTemplate = {
  id: "hazcom",
  title: "Hazard Communication Program (GHS)",
  vertical: "all",
  description: "Written HazCom program compliant with Cal/OSHA GHS-aligned standard. Covers chemical inventory, SDS management, labeling, and employee training.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount", "vertical"],
  refreshCycle: "annual",
  retentionYears: 30,
  disclaimer: "This Hazard Communication Program was generated by Protekon based on Cal/OSHA HazCom requirements (8 CCR 5194). It must be reviewed by the designated program administrator and updated whenever new chemicals are introduced to the workplace.",
  sections: [
    {
      heading: "1. Program Purpose and Scope",
      purpose: "State the purpose of the HazCom program, identify the workplace(s) covered, and confirm compliance with 8 CCR 5194 (GHS-aligned). Reference the employer's duty to provide a safe workplace free of chemical hazards.",
      requiredReferences: ["8 CCR 5194", "Labor Code §6360-6399.7"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "2. Responsible Persons",
      purpose: "Identify the HazCom program administrator(s) by name/title. Define responsibilities for maintaining chemical inventory, SDS library, training, and labeling compliance.",
      requiredReferences: ["8 CCR 5194(e)(1)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "3. Chemical Inventory",
      purpose: "Describe the process for maintaining a complete list of all hazardous chemicals present in the workplace. Include initial inventory procedure and how new chemicals are added.",
      requiredReferences: ["8 CCR 5194(e)(1)(A)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "4. Safety Data Sheets (SDS) Management",
      purpose: "Describe how SDSs are obtained, maintained, and made accessible to employees during each work shift. Include digital/physical SDS location and the process when an SDS is missing.",
      requiredReferences: ["8 CCR 5194(g)", "8 CCR 5194(e)(1)(B)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "5. Container Labeling",
      purpose: "Describe labeling requirements for original manufacturer containers and secondary/workplace containers. Include GHS label elements: product identifier, signal word, hazard statements, pictograms, precautionary statements.",
      requiredReferences: ["8 CCR 5194(f)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "6. Employee Training",
      purpose: "Describe initial and ongoing HazCom training. Must cover: how to read SDSs, label elements, physical/health hazards in work area, protective measures, and where to find the written program and SDS library.",
      requiredReferences: ["8 CCR 5194(h)"],
      targetWords: 350,
      alwaysInclude: true,
    },
    {
      heading: "7. Non-Routine Tasks and Unlabeled Pipes",
      purpose: "Describe procedures for non-routine tasks involving hazardous chemicals and how employees are informed about hazards of chemicals in unlabeled pipes.",
      requiredReferences: ["8 CCR 5194(e)(1)(C)", "8 CCR 5194(e)(1)(D)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "8. Multi-Employer Worksite Coordination",
      purpose: "If applicable, describe how hazard information is shared with contractors and other employers whose employees may be exposed to chemicals at this workplace.",
      requiredReferences: ["8 CCR 5194(e)(2)"],
      targetWords: 200,
      alwaysInclude: false,
    },
  ],
}

const OSHA_300_LOG_TEMPLATE: DocumentTemplate = {
  id: "osha-300-log",
  title: "OSHA 300 Log Compliance Program",
  vertical: "all",
  description: "Procedures for maintaining OSHA 300/300A/301 injury and illness logs per Cal/OSHA recordkeeping requirements.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This recordkeeping program was generated by Protekon. Employers with 10+ employees must maintain OSHA 300 Logs. Consult Cal/OSHA for industry-specific exemptions.",
  sections: [
    {
      heading: "1. Recordkeeping Obligations",
      purpose: "Identify which Cal/OSHA recordkeeping requirements apply to this employer. Reference 8 CCR 14300 and confirm the establishment is not exempt.",
      requiredReferences: ["8 CCR 14300.1", "8 CCR 14300.2"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "2. OSHA 300 Log Maintenance",
      purpose: "Describe procedures for entering work-related injuries and illnesses on the OSHA 300 Log within 7 calendar days. Define who is responsible for entries.",
      requiredReferences: ["8 CCR 14300.7", "8 CCR 14300.29"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "3. OSHA 301 Incident Reports",
      purpose: "Describe how individual incident reports (OSHA 301 or equivalent) are completed within 7 calendar days of notification of a recordable case.",
      requiredReferences: ["8 CCR 14300.7(b)(6)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "4. Annual Summary (OSHA 300A)",
      purpose: "Describe the annual summary process: review 300 Log, certify accuracy, post 300A from February 1 through April 30, and retain for 5 years.",
      requiredReferences: ["8 CCR 14300.32", "8 CCR 14300.33"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Reporting to Cal/OSHA",
      purpose: "Describe mandatory reporting requirements: fatalities within 8 hours, hospitalizations/amputations/eye loss within 24 hours. Include Cal/OSHA phone number and electronic reporting obligations.",
      requiredReferences: ["8 CCR 14300.35", "Labor Code §6409.1"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "6. Employee Access and Privacy",
      purpose: "Describe employee rights to access 300 Logs and how privacy concern cases (e.g., sexual assault, mental illness, HIV) are handled.",
      requiredReferences: ["8 CCR 14300.35(b)(2)", "8 CCR 14300.29(b)"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

const INCIDENT_INVESTIGATION_TEMPLATE: DocumentTemplate = {
  id: "incident-investigation",
  title: "Incident Investigation Procedures",
  vertical: "all",
  description: "Systematic procedures for investigating workplace incidents, identifying root causes, and implementing corrective actions per IIPP requirements.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This incident investigation procedure was generated by Protekon. It fulfills the investigation requirement of 8 CCR 3203(a)(6). Adapt forms and timelines to your specific operations.",
  sections: [
    {
      heading: "1. Purpose and Regulatory Basis",
      purpose: "State the purpose of the investigation procedure and its regulatory basis under the IIPP standard. Every employer must investigate workplace incidents to identify root causes.",
      requiredReferences: ["8 CCR 3203(a)(6)", "Labor Code §6401.7"],
      targetWords: 150,
      alwaysInclude: true,
    },
    {
      heading: "2. When to Investigate",
      purpose: "Define which events trigger a formal investigation: injuries, illnesses, near-misses, property damage, and hazardous conditions discovered by employees.",
      requiredReferences: ["8 CCR 3203(a)(6)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "3. Investigation Team and Responsibilities",
      purpose: "Identify who conducts investigations (supervisor, safety committee, etc.), their authority, and timeline for initiating investigation (within 24 hours).",
      requiredReferences: ["8 CCR 3203(a)(6)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "4. Investigation Steps",
      purpose: "Provide a step-by-step procedure: secure the scene, interview witnesses, document conditions, photograph/diagram the scene, identify root causes using a systematic method (5-Why or similar).",
      requiredReferences: ["8 CCR 3203(a)(6)"],
      targetWords: 400,
      alwaysInclude: true,
    },
    {
      heading: "5. Corrective Actions",
      purpose: "Describe how corrective actions are identified, assigned, tracked, and verified. Include timelines for interim measures vs. permanent corrections.",
      requiredReferences: ["8 CCR 3203(a)(4)", "8 CCR 3203(a)(6)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "6. Documentation and Recordkeeping",
      purpose: "Describe the investigation report format, required content, retention period (minimum 5 years for IIPP records), and how findings feed back into the IIPP and training programs.",
      requiredReferences: ["8 CCR 3203(b)", "8 CCR 14300.7"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

const TRAINING_RECORDS_FRAMEWORK_TEMPLATE: DocumentTemplate = {
  id: "training-records",
  title: "Training Records Framework",
  vertical: "all",
  description: "Comprehensive framework for documenting, tracking, and retaining employee safety training records per Cal/OSHA requirements.",
  jurisdiction: "cal-osha",
  requiredClientFields: ["businessName", "location", "employeeCount"],
  refreshCycle: "annual",
  retentionYears: 5,
  disclaimer: "This training records framework was generated by Protekon. It addresses the training documentation requirements of 8 CCR 3203(a)(7). Retain all training records for the duration of employment plus minimum retention periods.",
  sections: [
    {
      heading: "1. Training Program Overview",
      purpose: "Describe the employer's obligation to provide safety training and instruction under the IIPP standard. Identify required training topics based on the workplace hazards.",
      requiredReferences: ["8 CCR 3203(a)(7)", "Labor Code §6401.7"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "2. Required Training Topics",
      purpose: "List all Cal/OSHA-mandated training topics applicable to this employer: general IIPP awareness, hazard-specific training (HazCom, heat illness, etc.), emergency procedures, and new employee orientation.",
      requiredReferences: ["8 CCR 3203(a)(7)", "8 CCR 5194(h)"],
      targetWords: 300,
      alwaysInclude: true,
    },
    {
      heading: "3. Training Schedule and Frequency",
      purpose: "Define when training occurs: new hire orientation (before exposure), annual refreshers, when new hazards are introduced, and after incidents.",
      requiredReferences: ["8 CCR 3203(a)(7)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "4. Documentation Requirements",
      purpose: "Describe what each training record must contain: employee name, training date, topic, trainer name/qualifications, duration, and method (classroom, online, hands-on).",
      requiredReferences: ["8 CCR 3203(b)"],
      targetWords: 250,
      alwaysInclude: true,
    },
    {
      heading: "5. Sign-Off and Acknowledgment",
      purpose: "Describe the employee sign-off process: physical or electronic signature confirming attendance and understanding. Include the sign-off template format.",
      requiredReferences: ["8 CCR 3203(a)(7)"],
      targetWords: 200,
      alwaysInclude: true,
    },
    {
      heading: "6. Records Retention and Access",
      purpose: "Describe retention periods (minimum duration of employment for IIPP records, 30 years for exposure records), storage location, and employee/Cal/OSHA access rights.",
      requiredReferences: ["8 CCR 3203(b)", "8 CCR 3204"],
      targetWords: 200,
      alwaysInclude: true,
    },
  ],
}

// ---------------------------------------------------------------------------

/** All document templates organized by vertical → document type */
const TEMPLATE_REGISTRY: Record<string, DocumentTemplate[]> = {
  // Cross-vertical (every client gets these — the 8 platform-wide + hearing conservation)
  all: [
    WVPP_TEMPLATE,
    IIPP_TEMPLATE,
    EMERGENCY_ACTION_PLAN_TEMPLATE,
    HAZCOM_PROGRAM_TEMPLATE,
    HEAT_ILLNESS_PREVENTION_PLAN_TEMPLATE,
    OSHA_300_LOG_TEMPLATE,
    INCIDENT_INVESTIGATION_TEMPLATE,
    TRAINING_RECORDS_FRAMEWORK_TEMPLATE,
    HEARING_CONSERVATION_PROGRAM_TEMPLATE,
  ],
  // Vertical-specific
  construction: [
    FALL_PROTECTION_PLAN_TEMPLATE,
    SILICA_EXPOSURE_CONTROL_PLAN_TEMPLATE,
  ],
  healthcare: [
    BBP_EXPOSURE_CONTROL_PLAN_TEMPLATE,
    HIPAA_SRA_TEMPLATE,
    ATD_PLAN_TEMPLATE,
    BAA_TRACKER_TEMPLATE,
  ],
  manufacturing: [
    LOTO_PROGRAM_TEMPLATE,
    MACHINE_GUARDING_PROGRAM_TEMPLATE,
    CONFINED_SPACE_PROGRAM_TEMPLATE,
  ],
  agriculture: [
    WILDFIRE_SMOKE_PROTECTION_PLAN_TEMPLATE,
    PESTICIDE_SAFETY_PROGRAM_TEMPLATE,
  ],
  transportation: [FLEET_SAFETY_PROGRAM_TEMPLATE],
  wholesale: [PIT_SAFETY_PROGRAM_TEMPLATE],
  retail: [RETAIL_STORE_SAFETY_PROGRAM_TEMPLATE],
  hospitality: [HOSPITALITY_SAFETY_PROGRAM_TEMPLATE],
  "real-estate": [PROPERTY_COMPLIANCE_PROGRAM_TEMPLATE],
  "auto-services": [SPRAY_BOOTH_COMPLIANCE_PROGRAM_TEMPLATE],
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Get a specific document template by vertical and document type ID.
 * Checks vertical-specific templates first, then cross-vertical.
 */
export function getDocumentTemplate(
  vertical: string,
  documentTypeId: string
): DocumentTemplate | null {
  // Check vertical-specific first
  const verticalTemplates = TEMPLATE_REGISTRY[vertical] ?? []
  const found = verticalTemplates.find((t) => t.id === documentTypeId)
  if (found) return found

  // Fall back to cross-vertical
  const crossVertical = TEMPLATE_REGISTRY.all ?? []
  return crossVertical.find((t) => t.id === documentTypeId) ?? null
}

/**
 * Get all available document templates for a given vertical.
 * Returns cross-vertical templates + vertical-specific templates.
 */
export function getTemplatesForVertical(vertical: string): DocumentTemplate[] {
  const cross = TEMPLATE_REGISTRY.all ?? []
  const specific = TEMPLATE_REGISTRY[vertical] ?? []
  return [...cross, ...specific]
}

/**
 * Get all document type IDs available for a vertical.
 * Used by the document request UI to show available document types.
 */
export function getAvailableDocumentTypes(
  vertical: string
): { id: string; title: string; description: string; regulation: string; sectionCount: number }[] {
  return getTemplatesForVertical(vertical).map((t) => ({
    id: t.id,
    title: t.title,
    description: t.description,
    regulation: t.sections[0]?.requiredReferences[0] ?? "",
    sectionCount: t.sections.filter((s) => s.alwaysInclude).length,
  }))
}

/**
 * Validate that required client fields are present for a document type.
 * Call before invoking the AI generator.
 */
export function validateClientData(
  template: DocumentTemplate,
  clientData: Record<string, unknown>
): { valid: boolean; missing: string[] } {
  const missing = template.requiredClientFields.filter(
    (field) => !clientData[field]
  )
  return { valid: missing.length === 0, missing }
}

/**
 * Centralized label map for every template ID in the registry.
 * Single source of truth — documents.ts, UI components, and pipelines
 * all pull from here instead of maintaining separate hardcoded maps.
 */
export function getDocumentLabel(templateId: string): string {
  const allTemplates = Object.values(TEMPLATE_REGISTRY).flat()
  const found = allTemplates.find((t) => t.id === templateId)
  return found?.title ?? templateId.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
}

/**
 * Check if a template ID exists anywhere in the registry.
 * Used to enforce schema — reject unknown IDs before they create ghost documents.
 */
export function isValidTemplateId(templateId: string): boolean {
  const allTemplates = Object.values(TEMPLATE_REGISTRY).flat()
  return allTemplates.some((t) => t.id === templateId)
}

/**
 * Get the starter document set for a vertical + plan tier.
 * Replaces the generic "{vertical}-compliance-plan" pattern in intake-pipeline.
 * Returns real template IDs that pass through the AI generator with guardrails.
 */
export function getStarterDocuments(
  vertical: string,
  plan: "core" | "professional" | "multi-site"
): string[] {
  // Every client gets these 3 foundational documents
  const base: string[] = ["iipp", "wvpp", "incident-investigation"]

  // Professional + Multi-Site add EAP and HazCom
  if (plan === "professional" || plan === "multi-site") {
    base.push("eap", "hazcom")
  }

  // Multi-Site adds training framework and OSHA 300 log
  if (plan === "multi-site") {
    base.push("training-records", "osha-300-log")
  }

  // Add vertical-specific templates (all plan tiers)
  const verticalTemplates = TEMPLATE_REGISTRY[vertical] ?? []
  for (const t of verticalTemplates) {
    if (!base.includes(t.id)) {
      base.push(t.id)
    }
  }

  return base
}

/**
 * Get all verticals that have registered templates.
 */
export function getRegisteredVerticals(): string[] {
  return Object.keys(TEMPLATE_REGISTRY).filter((k) => k !== "all")
}

/**
 * Build the AI prompt section structure from a template.
 * This is what gets injected into the AI generator prompt so Claude
 * fills in content within the locked structure.
 */
export function buildSectionPrompt(template: DocumentTemplate): string {
  const lines = template.sections
    .filter((s) => s.alwaysInclude)
    .map(
      (s) =>
        `### ${s.heading}\nPurpose: ${s.purpose}\nRequired regulatory references: ${s.requiredReferences.join(", ")}\nTarget length: ~${s.targetWords} words`
    )

  return `Document: ${template.title}
Jurisdiction: ${template.jurisdiction === "cal-osha" ? "Cal/OSHA (California)" : template.jurisdiction === "federal-osha" ? "Federal OSHA" : template.jurisdiction === "multi" ? "Cal/OSHA + Federal" : template.jurisdiction.toUpperCase()}

Generate content for EACH of the following sections. Do NOT add, remove, or rename any sections. Fill in the body for each section using the purpose and required references as your guide.

${lines.join("\n\n")}

Output format: Return a JSON object with this structure:
{
  "title": "${template.title}",
  "sections": [
    { "heading": "exact heading from above", "body": "your generated content" }
  ],
  "recommendations": ["3-5 specific actionable recommendations based on the client's gaps"]
}

Rules:
- Every required regulatory reference MUST appear in the relevant section body
- Content must be site-specific using the business name, location, and employee count provided
- Do NOT add sections beyond those listed above
- Do NOT rename section headings
- Each section body should be approximately the target word count
- All regulatory references must be California-specific (Cal/OSHA Title 8 CCR, Labor Code)`
}
