import { PDFDocument, StandardFonts, rgb } from "pdf-lib"

const PAGE_WIDTH = 612
const PAGE_HEIGHT = 792
const MARGIN = 50
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2

const BRAND = {
  midnight: rgb(0.1, 0.1, 0.18),
  crimson: rgb(0.725, 0.11, 0.11),
  gold: rgb(0.835, 0.686, 0.322),
  steel: rgb(0.5, 0.5, 0.55),
  parchment: rgb(0.96, 0.953, 0.937),
  white: rgb(1, 1, 1),
}

interface SampleReport {
  title: string
  filename: string
  sections: { heading: string; items: string[] }[]
  footer: string
}

const REPORTS: Record<string, SampleReport> = {
  "SB 553 Workplace Violence Prevention Plan": {
    title: "Workplace Violence Prevention Plan",
    filename: "Protekon-Sample-WVPP.pdf",
    sections: [
      {
        heading: "1. Policy Statement & Scope",
        items: [
          "This Workplace Violence Prevention Plan (WVPP) is established pursuant to California Senate Bill 553 (Labor Code 6401.9).",
          "This plan applies to all employees, contractors, and visitors at [BUSINESS NAME] located at [ADDRESS].",
          "The employer designates [SAFETY COORDINATOR] as the person responsible for implementing this plan.",
          "This plan is effective as of [DATE] and will be reviewed annually or after any workplace violence incident.",
        ],
      },
      {
        heading: "2. Definitions",
        items: [
          "Workplace violence: Any act of violence or threat of violence that occurs in a place of employment (LC 6401.9(b)(1)).",
          "Types covered: Type 1 (criminal intent), Type 2 (customer/client), Type 3 (worker-on-worker), Type 4 (personal relationship).",
          "Threat of violence: Any statement or conduct that causes a reasonable person to fear for their safety.",
          "Emergency: Any workplace violence incident requiring immediate law enforcement or medical response.",
        ],
      },
      {
        heading: "3. Hazard Identification & Assessment",
        items: [
          "Initial assessment conducted [DATE] covering physical environment, staffing patterns, and incident history.",
          "Risk factors identified: public-facing operations, cash handling, late-night hours, isolated work areas.",
          "Assessment includes review of OSHA 300 logs, prior incident reports, and employee hazard reports.",
          "Reassessment triggered by: any incident, staffing changes, facility modifications, or annually.",
        ],
      },
      {
        heading: "4. Incident Response Procedures",
        items: [
          "Employees must report all incidents, threats, and suspicious activity to their immediate supervisor.",
          "Emergency response: Call 911, activate lockdown procedures, notify on-site security coordinator.",
          "Post-incident: Secure the scene, provide medical assistance, document details within 24 hours.",
          "All PII is automatically stripped from incident logs per PROTEKON data handling protocols.",
        ],
      },
      {
        heading: "5. Training Requirements",
        items: [
          "Initial training for all employees within 30 days of hire or plan implementation.",
          "Annual refresher training covering plan updates, new hazards, and reporting procedures.",
          "Training covers: recognition of risk factors, de-escalation techniques, reporting procedures, emergency response.",
          "Training records maintained for minimum 3 years per Cal/OSHA recordkeeping requirements.",
        ],
      },
      {
        heading: "6. Violent Incident Log",
        items: [
          "All workplace violence incidents are logged with: date, time, location, type, description, and response taken.",
          "Log excludes employee names and personally identifiable information (PII-stripped per SB 553 requirements).",
          "Incident logs are maintained for a minimum of 5 years.",
          "Logs are available for review by Cal/OSHA upon request.",
        ],
      },
    ],
    footer: "This is a SAMPLE document generated by PROTEKON. Your actual WVPP will be site-specific to your business address, industry risks, and workforce profile.",
  },

  "Construction Subcontractor Compliance Report": {
    title: "Subcontractor Compliance Report",
    filename: "Protekon-Sample-SubContractor-Report.pdf",
    sections: [
      {
        heading: "1. Subcontractor Verification Summary",
        items: [
          "Report period: [MONTH/YEAR] | General Contractor: [BUSINESS NAME]",
          "Total active subcontractors: 12 | Compliant: 10 | Non-compliant: 2 | Pending review: 0",
          "Overall compliance rate: 83.3% (target: 95%)",
          "Next review date: [30 days from generation]",
        ],
      },
      {
        heading: "2. CSLB License Verification",
        items: [
          "ABC Electrical (Lic #1048752) — Active, expires 08/2026, Class C-10 Electrical",
          "Pacific Plumbing (Lic #987654) — Active, expires 03/2027, Class C-36 Plumbing",
          "Valley Concrete (Lic #1123456) — SUSPENDED — Bonding lapsed 01/2026. Action required.",
          "Summit Roofing (Lic #876543) — Active, expires 11/2026, Class C-39 Roofing",
        ],
      },
      {
        heading: "3. Insurance Certificate Tracking",
        items: [
          "General Liability: 12/12 current (100%)",
          "Workers Compensation: 11/12 current (91.7%) — Valley Concrete expired 02/2026",
          "Auto Liability: 12/12 current (100%)",
          "Umbrella/Excess: 8/12 carry umbrella policies (not required, tracked for risk management)",
        ],
      },
      {
        heading: "4. Lien Waiver Status",
        items: [
          "Conditional waivers on file: 47/47 for current billing cycle",
          "Unconditional waivers received: 38/42 from prior cycle (90.5%)",
          "Outstanding unconditional waivers: Pacific Plumbing (2), Summit Roofing (2) — follow-up sent",
          "Joint check requirements: None active this period",
        ],
      },
      {
        heading: "5. Non-Compliance Actions Required",
        items: [
          "Valley Concrete: CSLB license suspended + WC insurance expired. Suspend from active projects until resolved.",
          "Pacific Plumbing: 2 unconditional lien waivers outstanding from prior billing cycle. 7-day notice sent.",
          "Recommended: Schedule quarterly sub compliance review meeting with project managers.",
          "All non-compliant subs notified via certified mail per contract Section 14.2.",
        ],
      },
    ],
    footer: "This is a SAMPLE report generated by PROTEKON. Your actual subcontractor compliance report will reflect your real subcontractor roster, CSLB records, and insurance certificates.",
  },

  "Property Management Municipal Compliance Pulse": {
    title: "Municipal Compliance Pulse Report",
    filename: "Protekon-Sample-Municipal-Pulse.pdf",
    sections: [
      {
        heading: "1. Portfolio Summary",
        items: [
          "Report period: [MONTH/YEAR] | Property Manager: [BUSINESS NAME]",
          "Properties monitored: 8 | Jurisdictions tracked: 4 (LA City, LA County, Long Beach, Pasadena)",
          "Active ordinance changes this period: 3 | Requiring action: 2 | Informational only: 1",
          "Compliance score: 94/100 (up from 91/100 last month)",
        ],
      },
      {
        heading: "2. Rent Control & Stabilization Updates",
        items: [
          "LA City RSO: Annual allowable increase set at 4% effective 07/2026 (up from 3% in 2025).",
          "Long Beach: New tenant anti-harassment ordinance effective 09/2026. Requires updated lease addendum.",
          "Pasadena: No changes this period. Current allowable increase remains 75% of CPI.",
          "Action required: Update Long Beach lease templates by 08/2026 to include anti-harassment language.",
        ],
      },
      {
        heading: "3. Habitability & Code Compliance",
        items: [
          "LA City: Proactive rental inspection program (SCEP) expanding to Zone 4 in Q3 2026.",
          "Properties affected: 1180 Maple Dr, 2245 Oak Ave (both in Zone 4 — expect inspection notice).",
          "Recommended: Schedule pre-inspection walkthrough for both properties within 30 days.",
          "Mold remediation standards updated per LA County Health Dept bulletin 2026-03. Review protocols.",
        ],
      },
      {
        heading: "4. Local Ordinance Changes",
        items: [
          "LA City Council File #24-0987: Proposed EV charging station requirement for multi-family buildings >10 units. In committee.",
          "Long Beach Municipal Code 8.101: Updated fire safety inspection frequency from 3-year to 2-year cycle.",
          "Pasadena: New short-term rental ordinance enforcement begins 06/2026. No portfolio properties affected.",
          "LA County: Updated swimming pool barrier requirements per Health & Safety Code Section 115920.",
        ],
      },
      {
        heading: "5. Action Items This Month",
        items: [
          "HIGH: Update Long Beach lease templates with anti-harassment addendum (deadline: 08/2026).",
          "MEDIUM: Schedule SCEP pre-inspection for 1180 Maple Dr and 2245 Oak Ave.",
          "MEDIUM: Review mold remediation protocols against updated LA County standards.",
          "LOW: Monitor EV charging requirement — no action until ordinance passes committee.",
        ],
      },
    ],
    footer: "This is a SAMPLE report generated by PROTEKON. Your actual municipal compliance pulse will reflect your real property portfolio, jurisdictions, and active ordinance changes.",
  },
}

function wrapText(text: string, font: Awaited<ReturnType<typeof PDFDocument.prototype.embedFont>>, size: number, maxWidth: number): string[] {
  const words = text.split(" ")
  const lines: string[] = []
  let current = ""
  for (const word of words) {
    const test = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(test, size) > maxWidth) {
      if (current) lines.push(current)
      current = word
    } else {
      current = test
    }
  }
  if (current) lines.push(current)
  return lines
}

export async function generateSamplePDF(reportTitle: string): Promise<{ buffer: Uint8Array; filename: string }> {
  const report = REPORTS[reportTitle]
  if (!report) {
    throw new Error(`Unknown report: ${reportTitle}`)
  }

  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold)
  const generatedDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })

  // --- Cover Page ---
  const cover = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])

  // Header band
  cover.drawRectangle({ x: 0, y: PAGE_HEIGHT - 120, width: PAGE_WIDTH, height: 120, color: BRAND.midnight })
  cover.drawText("PROTEKON", { x: MARGIN, y: PAGE_HEIGHT - 55, size: 28, font: fontBold, color: BRAND.parchment })
  cover.drawText("Sample Report", { x: MARGIN, y: PAGE_HEIGHT - 80, size: 14, font, color: BRAND.gold })

  // Accent line
  cover.drawRectangle({ x: MARGIN, y: PAGE_HEIGHT - 180, width: 60, height: 3, color: BRAND.crimson })

  // Title
  let y = PAGE_HEIGHT - 210
  const titleLines = wrapText(report.title, fontBold, 24, CONTENT_WIDTH)
  for (const line of titleLines) {
    cover.drawText(line, { x: MARGIN, y, size: 24, font: fontBold, color: BRAND.midnight })
    y -= 32
  }

  y -= 20
  cover.drawText(`Generated: ${generatedDate}`, { x: MARGIN, y, size: 10, font, color: BRAND.steel })
  y -= 16
  cover.drawText("SAMPLE DOCUMENT — For demonstration purposes", { x: MARGIN, y, size: 10, font: fontBold, color: BRAND.crimson })

  // Watermark
  cover.drawText("SAMPLE", {
    x: PAGE_WIDTH / 2 - 100,
    y: PAGE_HEIGHT / 2 - 40,
    size: 72,
    font: fontBold,
    color: rgb(0.9, 0.9, 0.9),
    opacity: 0.3,
  })

  // Footer
  const footerText = `PROTEKON | AI Compliance Officer | protekon.com`
  const footerWidth = font.widthOfTextAtSize(footerText, 8)
  cover.drawText(footerText, { x: (PAGE_WIDTH - footerWidth) / 2, y: 25, size: 8, font, color: BRAND.steel })

  // --- Content Pages ---
  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  y = PAGE_HEIGHT - MARGIN

  for (const section of report.sections) {
    // Check if we need a new page
    if (y < 200) {
      page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
      y = PAGE_HEIGHT - MARGIN
    }

    // Section heading
    page.drawRectangle({ x: MARGIN, y: y - 2, width: CONTENT_WIDTH, height: 1, color: BRAND.gold })
    y -= 18
    page.drawText(section.heading, { x: MARGIN, y, size: 13, font: fontBold, color: BRAND.midnight })
    y -= 24

    // Items
    for (const item of section.items) {
      const lines = wrapText(item, font, 10, CONTENT_WIDTH - 15)
      if (y < MARGIN + 40) {
        page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
        y = PAGE_HEIGHT - MARGIN
      }
      // Bullet
      page.drawText("\u2022", { x: MARGIN, y, size: 10, font, color: BRAND.crimson })
      for (const line of lines) {
        page.drawText(line, { x: MARGIN + 15, y, size: 10, font, color: BRAND.steel })
        y -= 16
      }
      y -= 4
    }

    y -= 16
  }

  // Disclaimer box
  if (y < 120) {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
    y = PAGE_HEIGHT - MARGIN
  }
  y -= 10
  page.drawRectangle({ x: MARGIN, y: y - 50, width: CONTENT_WIDTH, height: 60, color: rgb(0.97, 0.95, 0.93) })
  const disclaimerLines = wrapText(report.footer, font, 9, CONTENT_WIDTH - 20)
  let dy = y - 8
  for (const line of disclaimerLines) {
    page.drawText(line, { x: MARGIN + 10, y: dy, size: 9, font, color: BRAND.steel })
    dy -= 13
  }

  const buffer = await doc.save()
  return { buffer, filename: report.filename }
}
