import { PDFDocument, StandardFonts, rgb } from "pdf-lib"

const PAGE_WIDTH = 612
const PAGE_HEIGHT = 792
const MARGIN = 50
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2

const BRAND = {
  midnight: rgb(0.1, 0.1, 0.18),
  crimson: rgb(0.725, 0.11, 0.11),
  gold: rgb(0.835, 0.686, 0.322),
  steel: rgb(0.5, 0.5, 0.55),
  parchment: rgb(0.96, 0.953, 0.937),
  white: rgb(1, 1, 1),
}

interface SampleReport {
  title: string
  filename: string
  sections: { heading: string; items: string[] }[]
  footer: string
}

const REPORTS: Record<string, SampleReport> = {
  "SB 553 Workplace Violence Prevention Plan": {
    title: "Workplace Violence Prevention Plan",
    filename: "Protekon-Sample-WVPP.pdf",
    sections: [
      {
        heading: "1. Policy Statement & Scope",
        items: [
          "This Workplace Violence Prevention Plan (WVPP) is established pursuant to California Senate Bill 553 (Labor Code 6401.9).",
          "This plan applies to all employees, contractors, and visitors at [BUSINESS NAME] located at [ADDRESS].",
          "The employer designates [SAFETY COORDINATOR] as the person responsible for implementing this plan.",
          "This plan is effective as of [DATE] and will be reviewed annually or after any workplace violence incident.",
        ],
      },
      {
        heading: "2. Definitions",
        items: [
          "Workplace violence: Any act of violence or threat of violence that occurs in a place of employment (LC 6401.9(b)(1)).",
          "Types covered: Type 1 (criminal intent), Type 2 (customer/client), Type 3 (worker-on-worker), Type 4 (personal relationship).",
          "Threat of violence: Any statement or conduct that causes a reasonable person to fear for their safety.",
          "Emergency: Any workplace violence incident requiring immediate law enforcement or medical response.",
        ],
      },
      {
        heading: "3. Hazard Identification & Assessment",
        items: [
          "Initial assessment conducted [DATE] covering physical environment, staffing patterns, and incident history.",
          "Risk factors identified: public-facing operations, cash handling, late-night hours, isolated work areas.",
          "Assessment includes review of OSHA 300 logs, prior incident reports, and employee hazard reports.",
          "Reassessment triggered by: any incident, staffing changes, facility modifications, or annually.",
        ],
      },
      {
        heading: "4. Incident Response Procedures",
        items: [
          "Employees must report all incidents, threats, and suspicious activity to their immediate supervisor.",
          "Emergency response: Call 911, activate lockdown procedures, notify on-site security coordinator.",
          "Post-incident: Secure the scene, provide medical assistance, document details within 24 hours.",
          "All PII is automatically stripped from incident logs per PROTEKON data handling protocols.",
        ],
      },
      {
        heading: "5. Training Requirements",
        items: [
          "Initial training for all employees within 30 days of hire or plan implementation.",
          "Annual refresher training covering plan updates, new hazards, and reporting procedures.",
          "Training covers: recognition of risk factors, de-escalation techniques, reporting procedures, emergency response.",
          "Training records maintained for minimum 3 years per Cal/OSHA recordkeeping requirements.",
        ],
      },
      {
        heading: "6. Violent Incident Log",
        items: [
          "All workplace violence incidents are logged with: date, time, location, type, description, and response taken.",
          "Log excludes employee names and personally identifiable information (PII-stripped per SB 553 requirements).",
          "Incident logs are maintained for a minimum of 5 years.",
          "Logs are available for review by Cal/OSHA upon request.",
        ],
      },
    ],
    footer: "This is a SAMPLE document generated by PROTEKON. Your actual WVPP will be site-specific to your business address, industry risks, and workforce profile.",
  },

  "Construction Subcontractor Compliance Report": {
    title: "Subcontractor Compliance Report",
    filename: "Protekon-Sample-SubContractor-Report.pdf",
    sections: [
      {
        heading: "1. Subcontractor Verification Summary",
        items: [
          "Report period: [MONTH/YEAR] | General Contractor: [BUSINESS NAME]",
          "Total active subcontractors: 12 | Compliant: 10 | Non-compliant: 2 | Pending review: 0",
          "Overall compliance rate: 83.3% (target: 95%)",
          "Next review date: [30 days from generation]",
        ],
      },
      {
        heading: "2. CSLB License Verification",
        items: [
          "ABC Electrical (Lic #1048752) — Active, expires 08/2026, Class C-10 Electrical",
          "Pacific Plumbing (Lic #987654) — Active, expires 03/2027, Class C-36 Plumbing",
          "Valley Concrete (Lic #1123456) — SUSPENDED — Bonding lapsed 01/2026. Action required.",
          "Summit Roofing (Lic #876543) — Active, expires 11/2026, Class C-39 Roofing",
        ],
      },
      {
        heading: "3. Insurance Certificate Tracking",
        items: [
          "General Liability: 12/12 current (100%)",
          "Workers Compensation: 11/12 current (91.7%) — Valley Concrete expired 02/2026",
          "Auto Liability: 12/12 current (100%)",
          "Umbrella/Excess: 8/12 carry umbrella policies (not required, tracked for risk management)",
        ],
      },
      {
        heading: "4. Lien Waiver Status",
        items: [
          "Conditional waivers on file: 47/47 for current billing cycle",
          "Unconditional waivers received: 38/42 from prior cycle (90.5%)",
          "Outstanding unconditional waivers: Pacific Plumbing (2), Summit Roofing (2) — follow-up sent",
          "Joint check requirements: None active this period",
        ],
      },
      {
        heading: "5. Non-Compliance Actions Required",
        items: [
          "Valley Concrete: CSLB license suspended + WC insurance expired. Suspend from active projects until resolved.",
          "Pacific Plumbing: 2 unconditional lien waivers outstanding from prior billing cycle. 7-day notice sent.",
          "Recommended: Schedule quarterly sub compliance review meeting with project managers.",
          "All non-compliant subs notified via certified mail per contract Section 14.2.",
        ],
      },
    ],
    footer: "This is a SAMPLE report generated by PROTEKON. Your actual subcontractor compliance report will reflect your real subcontractor roster, CSLB records, and insurance certificates.",
  },

  "Property Management Municipal Compliance Pulse": {
    title: "Municipal Compliance Pulse Report",
    filename: "Protekon-Sample-Municipal-Pulse.pdf",
    sections: [
      {
        heading: "1. Portfolio Summary",
        items: [
          "Report period: [MONTH/YEAR] | Property Manager: [BUSINESS NAME]",
          "Properties monitored: 8 | Jurisdictions tracked: 4 (LA City, LA County, Long Beach, Pasadena)",
          "Active ordinance changes this period: 3 | Requiring action: 2 | Informational only: 1",
          "Compliance score: 94/100 (up from 91/100 last month)",
        ],
      },
      {
        heading: "2. Rent Control & Stabilization Updates",
        items: [
          "LA City RSO: Annual allowable increase set at 4% effective 07/2026 (up from 3% in 2025).",
          "Long Beach: New tenant anti-harassment ordinance effective 09/2026. Requires updated lease addendum.",
          "Pasadena: No changes this period. Current allowable increase remains 75% of CPI.",
          "Action required: Update Long Beach lease templates by 08/2026 to include anti-harassment language.",
        ],
      },
      {
        heading: "3. Habitability & Code Compliance",
        items: [
          "LA City: Proactive rental inspection program (SCEP) expanding to Zone 4 in Q3 2026.",
          "Properties affected: 1180 Maple Dr, 2245 Oak Ave (both in Zone 4 — expect inspection notice).",
          "Recommended: Schedule pre-inspection walkthrough for both properties within 30 days.",
          "Mold remediation standards updated per LA County Health Dept bulletin 2026-03. Review protocols.",
        ],
      },
      {
        heading: "4. Local Ordinance Changes",
        items: [
          "LA City Council File #24-0987: Proposed EV charging station requirement for multi-family buildings >10 units. In committee.",
          "Long Beach Municipal Code 8.101: Updated fire safety inspection frequency from 3-year to 2-year cycle.",
          "Pasadena: New short-term rental ordinance enforcement begins 06/2026. No portfolio properties affected.",
          "LA County: Updated swimming pool barrier requirements per Health & Safety Code Section 115920.",
        ],
      },
      {
        heading: "5. Action Items This Month",
        items: [
          "HIGH: Update Long Beach lease templates with anti-harassment addendum (deadline: 08/2026).",
          "MEDIUM: Schedule SCEP pre-inspection for 1180 Maple Dr and 2245 Oak Ave.",
          "MEDIUM: Review mold remediation protocols against updated LA County standards.",
          "LOW: Monitor EV charging requirement — no action until ordinance passes committee.",
        ],
      },
    ],
    footer: "This is a SAMPLE report generated by PROTEKON. Your actual municipal compliance pulse will reflect your real property portfolio, jurisdictions, and active ordinance changes.",
  },

  "Injury & Illness Prevention Program (IIPP)": {
    title: "Injury & Illness Prevention Program",
    filename: "Protekon-Sample-IIPP.pdf",
    sections: [
      {
        heading: "1. Responsibility",
        items: [
          "This Injury & Illness Prevention Program is established pursuant to 8 CCR §3203.",
          "[SAFETY COORDINATOR NAME] is the designated person with authority and responsibility for implementing this Program.",
          "Managers and supervisors are responsible for implementing and maintaining the IIPP in their work areas.",
          "All employees are responsible for following safe work practices and reporting unsafe conditions.",
        ],
      },
      {
        heading: "2. Compliance System",
        items: [
          "Recognition of safe and healthful work practices through [RECOGNITION PROGRAM e.g., monthly safety awards].",
          "Training programs conducted at hire and whenever new hazards are introduced.",
          "Retraining when supervisors observe unsafe performance.",
          "Disciplinary action per [COMPANY POLICY] for willful violations — documented in writing.",
        ],
      },
      {
        heading: "3. Communication",
        items: [
          "New-hire safety orientation covers hazards, controls, and reporting procedures.",
          "Toolbox talks held [FREQUENCY — e.g., weekly] covering current site hazards and seasonal risks.",
          "Anonymous hazard reporting via [METHOD — suggestion box, hotline, email] with no retaliation.",
          "Safety committee meets [FREQUENCY] with employee representation required.",
        ],
      },
      {
        heading: "4. Hazard Assessment",
        items: [
          "Initial site inspection completed [DATE] documenting all known hazards.",
          "Scheduled periodic inspections conducted [FREQUENCY — at least quarterly].",
          "Inspections triggered by new equipment, processes, substances, or workplace layout changes.",
          "Inspection findings logged with corrective action assignments and target dates.",
        ],
      },
      {
        heading: "5. Accident / Exposure Investigation",
        items: [
          "All injuries, illnesses, and near-misses investigated within 24 hours of occurrence.",
          "Investigation documents: employee(s) involved, date/time/location, task performed, sequence of events, contributing factors, root cause.",
          "Corrective actions assigned with owner and completion date; tracked to closure.",
          "Serious injuries reported to Cal/OSHA within 8 hours per Labor Code §6409.1.",
        ],
      },
      {
        heading: "6. Hazard Correction",
        items: [
          "Imminent hazards corrected immediately; affected employees removed until safe.",
          "Non-imminent hazards corrected per priority schedule — documented with target date.",
          "Engineering controls preferred over administrative controls; PPE as last resort.",
          "Corrective action effectiveness verified by follow-up inspection.",
        ],
      },
      {
        heading: "7. Training",
        items: [
          "Training provided at hire, when assigned new duties, when new hazards introduced, and annually.",
          "Topics include: general safe work practices, specific hazards of the job, emergency procedures, reporting unsafe conditions.",
          "Training records include: employee name, date, topic, trainer, and competency verification method.",
          "All training records retained for minimum 3 years per Cal/OSHA recordkeeping requirements.",
        ],
      },
      {
        heading: "8. Recordkeeping",
        items: [
          "Inspection records retained for at least 1 year.",
          "Training records retained for at least 3 years.",
          "Accident investigation records retained for at least 5 years.",
          "All records available to employees, their representatives, and Cal/OSHA upon request.",
        ],
      },
    ],
    footer: "This is a SAMPLE IIPP generated by PROTEKON. Your actual IIPP will be site-specific to your operations, NAICS hazards, and organizational structure — and kept current with quarterly inspections and training updates.",
  },

  "SB 553 Violent Incident Log (Sample)": {
    title: "Violent Incident Log — PII-Stripped Sample",
    filename: "Protekon-Sample-Violent-Incident-Log.pdf",
    sections: [
      {
        heading: "About This Sample",
        items: [
          "SB 553 requires a Violent Incident Log for every incident of workplace violence, threat, and near-miss.",
          "Labor Code §6401.9(e) mandates that the log EXCLUDE personally identifiable information: no employee names, witness names, patient/client identifiers, or medical details.",
          "Log entries must be retained for a minimum of 5 years and be available to employees and Cal/OSHA upon request.",
          "This sample shows three representative entries with correct PII redaction — never include names or clinical details.",
        ],
      },
      {
        heading: "Entry 1 — Type 2 (Customer/Client)",
        items: [
          "Date: 2026-02-14    Time: 14:22    Location: Front reception area",
          "Incident type: Type 2 (verbal threat from customer)",
          "Description: Individual became agitated during service dispute, verbally threatened a staff member, and refused to leave for approximately 4 minutes.",
          "Consequences: No physical injury. Staff member felt unsafe. Law enforcement called; individual departed before arrival.",
          "Where, when, how — without PII: Public-facing reception during business hours; trigger was billing disagreement; resolved when staff member withdrew and supervisor intervened.",
          "Actions taken: Panic button tested and verified functional. Staff debrief conducted. Signage about trespass updated.",
        ],
      },
      {
        heading: "Entry 2 — Type 3 (Worker-on-Worker)",
        items: [
          "Date: 2026-03-02    Time: 09:48    Location: Warehouse loading dock",
          "Incident type: Type 3 (threatening behavior between coworkers)",
          "Description: Two employees engaged in heated verbal altercation escalating to one employee raising a fist. No contact.",
          "Consequences: No injuries. Both employees separated by supervisor within 30 seconds. One employee sent home for the shift.",
          "Where, when, how — without PII: Shift-change period in a high-throughput work area; contributing factor was scheduling dispute; resolved through supervisor intervention and follow-up HR investigation.",
          "Actions taken: De-escalation refresher scheduled for all dock staff. Anonymous hazard-report box installed.",
        ],
      },
      {
        heading: "Entry 3 — Type 1 (Criminal Intent)",
        items: [
          "Date: 2026-03-18    Time: 22:05    Location: Employee parking lot",
          "Incident type: Type 1 (attempted robbery)",
          "Description: Individual approached employee exiting building and demanded belongings. Employee complied; individual fled.",
          "Consequences: No physical injury. Minor property loss. Police report filed under case [REDACTED].",
          "Where, when, how — without PII: Poorly lit area of lot during late-shift departure; trigger was opportunity (isolated worker); resolved when individual fled on foot.",
          "Actions taken: Parking lot lighting audit scheduled within 72 hours. Walk-to-car buddy system implemented for all shifts ending after 21:00. Exterior cameras upgraded.",
        ],
      },
      {
        heading: "Required Log Fields — Compliance Checklist",
        items: [
          "Date and time of incident — REQUIRED",
          "Location where incident occurred — REQUIRED (workplace area, not home address)",
          "Workplace violence type (Type 1, 2, 3, or 4) — REQUIRED",
          "Detailed description of circumstances — REQUIRED (NO names, NO clinical details)",
          "Who the incident involved — BY ROLE ONLY (e.g., 'employee,' 'customer,' 'contractor' — never names)",
          "Consequences and actions taken — REQUIRED",
          "Signage / training / control changes resulting from the incident — STRONGLY RECOMMENDED",
        ],
      },
    ],
    footer: "This is a SAMPLE Violent Incident Log. Your actual log will be generated by PROTEKON from incidents you file — we automatically strip PII before persisting log entries so your record-keeping stays compliant with SB 553 Labor Code §6401.9(e) by default.",
  },

  "Audit-Ready Compliance Package": {
    title: "Audit-Ready Compliance Package — Table of Contents",
    filename: "Protekon-Sample-Audit-Package-TOC.pdf",
    sections: [
      {
        heading: "What This Package Is",
        items: [
          "The Audit-Ready Compliance Package is what PROTEKON hands you the day Cal/OSHA walks in — or the day your insurance underwriter asks for proof.",
          "It consolidates every required record into one deliverable, organized the way inspectors look for things.",
          "Generated on demand from your live data; updated automatically as your compliance posture changes.",
          "Every item below is cross-referenced to its enabling standard, and every timestamp is preserved for chain-of-custody.",
        ],
      },
      {
        heading: "Section A — Written Programs",
        items: [
          "A1. Injury & Illness Prevention Program (8 CCR §3203)",
          "A2. Workplace Violence Prevention Plan (Labor Code §6401.9)",
          "A3. Heat Illness Prevention Plan (8 CCR §3395) — if outdoor work applies",
          "A4. Hazard Communication Program (8 CCR §5194)",
          "A5. Emergency Action Plan (8 CCR §3220)",
          "A6. Vertical-specific written programs (e.g., Fall Protection, LOTO, HIPAA — included as applicable to your NAICS)",
        ],
      },
      {
        heading: "Section B — Training Records",
        items: [
          "B1. Roster of employees with training status by required topic",
          "B2. Completion certificates and sign-off sheets (last 3 years)",
          "B3. New-hire orientation records",
          "B4. Annual refresher records",
          "B5. Topic-specific training (WVPP, IIPP, heat illness, PIT operator, etc.)",
          "B6. Trainer qualifications and curriculum documentation",
        ],
      },
      {
        heading: "Section C — Incident & Violence Documentation",
        items: [
          "C1. OSHA 300 Log (current year + prior 5 years)",
          "C2. OSHA 301 Incident Reports",
          "C3. OSHA 300A Annual Summary (posted Feb 1 – Apr 30)",
          "C4. SB 553 Violent Incident Log (PII-stripped)",
          "C5. Incident investigation reports with root-cause and corrective actions",
          "C6. 8-hour Cal/OSHA notifications for serious injuries (LC §6409.1)",
        ],
      },
      {
        heading: "Section D — Inspections & Hazard Assessments",
        items: [
          "D1. Scheduled workplace inspection reports (quarterly at minimum)",
          "D2. Hazard assessment for PPE selection (8 CCR §3380)",
          "D3. Respiratory protection program hazard assessment (if applicable)",
          "D4. Ergonomics evaluations",
          "D5. Noise exposure assessments (if applicable)",
          "D6. Corrective action log with target dates and verification of closure",
        ],
      },
      {
        heading: "Section E — Compliance Calendar & Posters",
        items: [
          "E1. Required poster compliance confirmation (Cal/OSHA, DLSE, DFEH, federal)",
          "E2. Annual posting dates (OSHA 300A, IIPP, WVPP review date)",
          "E3. Certification expirations (forklift, DQ files, etc.)",
          "E4. Upcoming refresher training due dates",
          "E5. Permanent Standard Dec 31, 2026 readiness checklist",
        ],
      },
      {
        heading: "Section F — Vertical-Specific Appendices",
        items: [
          "F1. Construction: CSLB license verification, sub COIs, fall protection plans",
          "F2. Healthcare: HIPAA SRA, BAA register, ATD plan, BBP exposure control",
          "F3. Manufacturing: LOTO procedures, machine guarding audits, confined space program",
          "F4. Real Estate: Municipal ordinance compliance log, rent control tracking",
          "F5. Transportation: DQ files, fleet safety, hours-of-service records",
          "F6. Retail / Hospitality / Warehouse: PIT certifications, store-safety programs",
        ],
      },
    ],
    footer: "This is a SAMPLE Audit-Ready Package table of contents. Your actual package will be generated on demand from your live data — every section populated from your documents, logs, and training records with cross-references to enabling standards.",
  },

  "Quarterly Compliance Review": {
    title: "Quarterly Compliance Review Report",
    filename: "Protekon-Sample-Quarterly-Review.pdf",
    sections: [
      {
        heading: "Review Period",
        items: [
          "Reporting period: 2026-01-01 through 2026-03-31",
          "Review conducted by: PROTEKON (AI Compliance Officer) with [CLIENT DESIGNEE] co-sign",
          "Next review scheduled: 2026-07-15",
          "Professional tier — Included quarterly as part of service. Multi-Site tier — Consolidated across all locations.",
        ],
      },
      {
        heading: "Executive Summary",
        items: [
          "Compliance score: 94% (up 6 points from prior quarter)",
          "Gaps closed this quarter: 7 of 9",
          "New regulatory updates affecting this client: 3 (all absorbed into active plans)",
          "Training completions: 18 of 22 required refreshers completed on schedule",
          "Incidents logged: 2 (Type 2 verbal threat, Type 3 worker-on-worker — both closed with corrective actions)",
        ],
      },
      {
        heading: "Regulatory Intelligence — What Changed This Quarter",
        items: [
          "Cal/OSHA announced Dec 31, 2026 permanent workplace violence standard (current interim remains in force) — no action required until Q4 planning",
          "Cal/OSHA Indoor Heat Illness enforcement emphasis extended through 2026 — applies to [AFFECTED AREAS]",
          "Fall Protection NEP renewed by federal OSHA — affects rooftop and elevated work",
          "Impact to this client: All three absorbed into existing plans. No new written program changes required.",
        ],
      },
      {
        heading: "Gap Closure Summary",
        items: [
          "CLOSED: Annual IIPP review and signoff (overdue -> current)",
          "CLOSED: WVPP refresher training for 4 new hires (completed in Feb)",
          "CLOSED: Fire extinguisher inspection gap (vendor rescheduled and verified)",
          "CLOSED: Heat illness plan acclimatization procedure (added to written plan)",
          "CLOSED: Forklift operator recertifications (3 operators, all current)",
          "CLOSED: Poster compliance refresh (DLSE updated minimum wage poster rolled out)",
          "CLOSED: Incident investigation documentation template (standardized across sites)",
          "OPEN: Ergonomics evaluation for new workstation layout — scheduled Q2",
          "OPEN: HIPAA SRA annual refresh — scheduled May 2026 per CMS guidance cycle",
        ],
      },
      {
        heading: "Enforcement Intelligence — Your NAICS, Your Region",
        items: [
          "Cal/OSHA citations in your NAICS / zip-code region this quarter: 47",
          "Average penalty for serious violations in your industry: $14,200",
          "Top citation this quarter in your industry: Inadequate written IIPP (§3203)",
          "Your exposure: No open Cal/OSHA cases. No open insurance-driven audits. No open citations.",
          "Peer benchmark: You rank in the top 15% for training completion timeliness among same-NAICS clients.",
        ],
      },
      {
        heading: "Q2 Priorities (Next 90 Days)",
        items: [
          "Complete ergonomics evaluation of new workstation layout (owner: Operations)",
          "Execute HIPAA Security Risk Assessment refresh (owner: Compliance)",
          "Schedule Permanent Standard Dec 31, 2026 readiness workshop (owner: PROTEKON)",
          "Implement parking lot lighting upgrade from Q1 incident corrective action (owner: Facilities)",
          "Renew 2 forklift operator certifications scheduled to expire in June (owner: Training)",
        ],
      },
      {
        heading: "Acknowledgement",
        items: [
          "This report documents our compliance posture for Q1 2026. PROTEKON retains the AI Compliance Officer records; the client retains the signed acknowledgement.",
          "By signing, the client confirms review of gaps, closures, and priorities and accepts the Q2 plan.",
          "Client signature: _________________________    Date: _____________",
          "PROTEKON signature: Automated — retained in system of record",
        ],
      },
    ],
    footer: "This is a SAMPLE Quarterly Review. Your actual quarterly review will pull from your live compliance data: your score trend, your incidents, your gap closures, your jurisdiction's enforcement signals, and your next-90-days action plan — co-signed with you.",
  },
}

function wrapText(text: string, font: Awaited<ReturnType<typeof PDFDocument.prototype.embedFont>>, size: number, maxWidth: number): string[] {
  const words = text.split(" ")
  const lines: string[] = []
  let current = ""
  for (const word of words) {
    const test = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(test, size) > maxWidth) {
      if (current) lines.push(current)
      current = word
    } else {
      current = test
    }
  }
  if (current) lines.push(current)
  return lines
}

export async function generateSamplePDF(reportTitle: string): Promise<{ buffer: Uint8Array; filename: string }> {
  const report = REPORTS[reportTitle]
  if (!report) {
    throw new Error(`Unknown report: ${reportTitle}`)
  }

  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold)
  const generatedDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })

  // --- Cover Page ---
  const cover = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])

  // Header band
  cover.drawRectangle({ x: 0, y: PAGE_HEIGHT - 120, width: PAGE_WIDTH, height: 120, color: BRAND.midnight })
  cover.drawText("PROTEKON", { x: MARGIN, y: PAGE_HEIGHT - 55, size: 28, font: fontBold, color: BRAND.parchment })
  cover.drawText("Sample Report", { x: MARGIN, y: PAGE_HEIGHT - 80, size: 14, font, color: BRAND.gold })

  // Accent line
  cover.drawRectangle({ x: MARGIN, y: PAGE_HEIGHT - 180, width: 60, height: 3, color: BRAND.crimson })

  // Title
  let y = PAGE_HEIGHT - 210
  const titleLines = wrapText(report.title, fontBold, 24, CONTENT_WIDTH)
  for (const line of titleLines) {
    cover.drawText(line, { x: MARGIN, y, size: 24, font: fontBold, color: BRAND.midnight })
    y -= 32
  }

  y -= 20
  cover.drawText(`Generated: ${generatedDate}`, { x: MARGIN, y, size: 10, font, color: BRAND.steel })
  y -= 16
  cover.drawText("SAMPLE DOCUMENT — For demonstration purposes", { x: MARGIN, y, size: 10, font: fontBold, color: BRAND.crimson })

  // Watermark
  cover.drawText("SAMPLE", {
    x: PAGE_WIDTH / 2 - 100,
    y: PAGE_HEIGHT / 2 - 40,
    size: 72,
    font: fontBold,
    color: rgb(0.9, 0.9, 0.9),
    opacity: 0.3,
  })

  // Footer
  const footerText = `PROTEKON | AI Compliance Officer | protekon.com`
  const footerWidth = font.widthOfTextAtSize(footerText, 8)
  cover.drawText(footerText, { x: (PAGE_WIDTH - footerWidth) / 2, y: 25, size: 8, font, color: BRAND.steel })

  // --- Content Pages ---
  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  y = PAGE_HEIGHT - MARGIN

  for (const section of report.sections) {
    // Check if we need a new page
    if (y < 200) {
      page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
      y = PAGE_HEIGHT - MARGIN
    }

    // Section heading
    page.drawRectangle({ x: MARGIN, y: y - 2, width: CONTENT_WIDTH, height: 1, color: BRAND.gold })
    y -= 18
    page.drawText(section.heading, { x: MARGIN, y, size: 13, font: fontBold, color: BRAND.midnight })
    y -= 24

    // Items
    for (const item of section.items) {
      const lines = wrapText(item, font, 10, CONTENT_WIDTH - 15)
      if (y < MARGIN + 40) {
        page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
        y = PAGE_HEIGHT - MARGIN
      }
      // Bullet
      page.drawText("\u2022", { x: MARGIN, y, size: 10, font, color: BRAND.crimson })
      for (const line of lines) {
        page.drawText(line, { x: MARGIN + 15, y, size: 10, font, color: BRAND.steel })
        y -= 16
      }
      y -= 4
    }

    y -= 16
  }

  // Disclaimer box
  if (y < 120) {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
    y = PAGE_HEIGHT - MARGIN
  }
  y -= 10
  page.drawRectangle({ x: MARGIN, y: y - 50, width: CONTENT_WIDTH, height: 60, color: rgb(0.97, 0.95, 0.93) })
  const disclaimerLines = wrapText(report.footer, font, 9, CONTENT_WIDTH - 20)
  let dy = y - 8
  for (const line of disclaimerLines) {
    page.drawText(line, { x: MARGIN + 10, y: dy, size: 9, font, color: BRAND.steel })
    dy -= 13
  }

  const buffer = await doc.save()
  return { buffer, filename: report.filename }
}
