import { defineField, defineType } from 'sanity'

export const blogPost = defineType({
  name: 'blogPost',
  title: 'Blog Post',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string', validation: (r) => r.required() }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title', maxLength: 96 }, validation: (r) => r.required() }),
    defineField({ name: 'author', title: 'Author', type: 'reference', to: [{ type: 'blogAuthor' }] }),
    defineField({ name: 'excerpt', title: 'Excerpt', type: 'text', rows: 3 }),
    defineField({ name: 'coverImage', title: 'Cover Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'body', title: 'Body', type: 'array', of: [{ type: 'block' }, { type: 'image', options: { hotspot: true } }] }),
    defineField({ name: 'categories', title: 'Categories', type: 'array', of: [{ type: 'reference', to: [{ type: 'blogCategory' }] }] }),
    defineField({
      name: 'regulatoryDomain',
      title: 'Regulatory Domain',
      type: 'string',
      options: {
        list: [
          { title: 'SB 553 / WVPP', value: 'sb-553' },
          { title: 'Cal/OSHA', value: 'cal-osha' },
          { title: 'Federal OSHA', value: 'federal-osha' },
          { title: 'HIPAA', value: 'hipaa' },
          { title: 'Subcontractor Risk', value: 'subcontractor-risk' },
          { title: 'Municipal Compliance', value: 'municipal' },
          { title: 'WVP Multi-State', value: 'wvp-multistate' },
        ],
      },
    }),
    defineField({
      name: 'industries',
      title: 'Industries',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          // Tier 1
          { title: 'Agriculture', value: 'agriculture' },
          { title: 'Arts/Entertainment', value: 'arts-entertainment' },
          { title: 'Automotive Services', value: 'automotive-services' },
          { title: 'Building Services', value: 'building-services' },
          { title: 'Construction', value: 'construction' },
          { title: 'Education', value: 'education' },
          { title: 'Healthcare', value: 'healthcare' },
          { title: 'Hospitality', value: 'hospitality' },
          { title: 'Manufacturing', value: 'manufacturing' },
          { title: 'Public Administration', value: 'public-administration' },
          { title: 'Retail Trade', value: 'retail-trade' },
          { title: 'Transportation', value: 'transportation' },
          { title: 'Utilities', value: 'utilities' },
          { title: 'Waste & Environmental', value: 'waste-environmental' },
          { title: 'Wholesale Trade', value: 'wholesale-trade' },
          // Tier 2
          { title: 'Business Support Services', value: 'business-support-services' },
          { title: 'Equipment Repair', value: 'equipment-repair' },
          { title: 'Facilities Management', value: 'facilities-management' },
          { title: 'Information/Telecom', value: 'information-telecom' },
          { title: 'Laundry & Drycleaning', value: 'laundry-drycleaning' },
          { title: 'Mining', value: 'mining' },
          { title: 'Professional Services', value: 'professional-services' },
          { title: 'Real Estate', value: 'real-estate' },
          { title: 'Staffing & Employment', value: 'staffing-employment' },
          { title: 'Warehouse', value: 'warehouse' },
          // Tier 3
          { title: 'Personal Services', value: 'personal-services' },
          { title: 'Security Services', value: 'security-services' },
        ],
      },
    }),
    defineField({
      name: 'keywordCluster',
      title: 'Keyword Cluster',
      type: 'string',
      options: {
        list: [
          { title: 'Fine Panic', value: 'fine-panic' },
          { title: 'Privacy Trap', value: 'privacy-trap' },
          { title: 'Post-Incident', value: 'post-incident' },
          { title: 'Vendor Roadblocks', value: 'vendor-roadblocks' },
          { title: 'DIY Failure', value: 'diy-failure' },
          { title: 'Annual Review', value: 'annual-review' },
          { title: 'Permanent Standard', value: 'permanent-standard' },
          { title: 'Industry-Specific', value: 'industry-specific' },
          { title: 'Training', value: 'training' },
          { title: 'Recordkeeping', value: 'recordkeeping' },
          { title: 'HR Research', value: 'hr-research' },
          { title: 'Legal Crossover', value: 'legal-crossover' },
          { title: 'Geo-Targeted', value: 'geo-targeted' },
          { title: 'Competitor', value: 'competitor' },
          { title: 'Discovery', value: 'discovery' },
        ],
      },
    }),
    defineField({
      name: 'contentTier',
      title: 'Content Tier',
      type: 'string',
      options: {
        list: [
          { title: 'Pillar', value: 'pillar' },
          { title: 'Cluster', value: 'cluster' },
          { title: 'Vertical', value: 'vertical' },
          { title: 'Comparison', value: 'comparison' },
          { title: 'Data Briefing', value: 'data-briefing' },
          { title: 'How-To', value: 'how-to' },
          { title: 'Checklist Article', value: 'checklist-article' },
          { title: 'State Guide', value: 'state-guide' },
        ],
      },
    }),
    defineField({ name: 'publishedAt', title: 'Published At', type: 'datetime', initialValue: () => new Date().toISOString() }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'object',
      fields: [
        defineField({ name: 'metaTitle', title: 'Meta Title', type: 'string' }),
        defineField({ name: 'metaDescription', title: 'Meta Description', type: 'text', rows: 2 }),
      ],
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'author.name', media: 'coverImage' },
  },
})
