import { defineField, defineType } from 'sanity'

export const regulatoryUpdate = defineType({
  name: 'regulatoryUpdate',
  title: 'Regulatory Update',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string', validation: (r) => r.required() }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title', maxLength: 96 }, validation: (r) => r.required() }),
    defineField({ name: 'body', title: 'Body', type: 'array', of: [{ type: 'block' }, { type: 'image', options: { hotspot: true } }] }),
    defineField({ name: 'source', title: 'Source', type: 'string', description: 'e.g. Cal/OSHA, DIR, Legislature' }),
    defineField({ name: 'effectiveDate', title: 'Effective Date', type: 'date' }),
    defineField({
      name: 'severity',
      title: 'Severity',
      type: 'string',
      options: { list: ['critical', 'high', 'medium', 'low', 'informational'] },
    }),
    defineField({
      name: 'industries',
      title: 'Affected Industries',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'All Industries', value: 'all' },
          { title: 'Agriculture', value: 'agriculture' },
          { title: 'Arts/Entertainment', value: 'arts-entertainment' },
          { title: 'Automotive Services', value: 'automotive-services' },
          { title: 'Building Services', value: 'building-services' },
          { title: 'Construction', value: 'construction' },
          { title: 'Education', value: 'education' },
          { title: 'Healthcare', value: 'healthcare' },
          { title: 'Hospitality', value: 'hospitality' },
          { title: 'Manufacturing', value: 'manufacturing' },
          { title: 'Public Administration', value: 'public-administration' },
          { title: 'Retail Trade', value: 'retail-trade' },
          { title: 'Transportation', value: 'transportation' },
          { title: 'Utilities', value: 'utilities' },
          { title: 'Waste & Environmental', value: 'waste-environmental' },
          { title: 'Wholesale Trade', value: 'wholesale-trade' },
          { title: 'Business Support Services', value: 'business-support-services' },
          { title: 'Equipment Repair', value: 'equipment-repair' },
          { title: 'Facilities Management', value: 'facilities-management' },
          { title: 'Information/Telecom', value: 'information-telecom' },
          { title: 'Laundry & Drycleaning', value: 'laundry-drycleaning' },
          { title: 'Mining', value: 'mining' },
          { title: 'Professional Services', value: 'professional-services' },
          { title: 'Real Estate', value: 'real-estate' },
          { title: 'Staffing & Employment', value: 'staffing-employment' },
          { title: 'Warehouse', value: 'warehouse' },
          { title: 'Personal Services', value: 'personal-services' },
          { title: 'Security Services', value: 'security-services' },
        ],
      },
    }),
    defineField({ name: 'jurisdiction', title: 'Jurisdiction', type: 'string', description: 'e.g. Federal, California, Connecticut, Municipal' }),
    defineField({ name: 'standard', title: 'Standard/Code', type: 'string', description: 'e.g. SB 553, T8 CCR 3203' }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'severity' },
  },
})
