import { defineField, defineType } from 'sanity'

export const resource = defineType({
  name: 'resource',
  title: 'Resource',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string', validation: (r) => r.required() }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title', maxLength: 96 }, validation: (r) => r.required() }),
    defineField({
      name: 'resourceType',
      title: 'Type',
      type: 'string',
      options: { list: ['guide', 'template', 'webinar', 'article', 'checklist', 'whitepaper', 'playbook', 'briefing', 'assessment'] },
      validation: (r) => r.required(),
    }),
    defineField({ name: 'excerpt', title: 'Excerpt', type: 'text', rows: 3 }),
    defineField({ name: 'coverImage', title: 'Cover Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'body', title: 'Body', type: 'array', of: [{ type: 'block' }, { type: 'image', options: { hotspot: true } }] }),
    defineField({ name: 'categories', title: 'Categories', type: 'array', of: [{ type: 'reference', to: [{ type: 'resourceCategory' }] }] }),
    defineField({
      name: 'regulatoryDomain',
      title: 'Regulatory Domain',
      type: 'string',
      options: {
        list: [
          { title: 'SB 553 / WVPP', value: 'sb-553' },
          { title: 'Cal/OSHA', value: 'cal-osha' },
          { title: 'Federal OSHA', value: 'federal-osha' },
          { title: 'HIPAA', value: 'hipaa' },
          { title: 'Subcontractor Risk', value: 'subcontractor-risk' },
          { title: 'Municipal Compliance', value: 'municipal' },
          { title: 'WVP Multi-State', value: 'wvp-multistate' },
        ],
      },
    }),
    defineField({
      name: 'industries',
      title: 'Industries',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Agriculture', value: 'agriculture' },
          { title: 'Arts/Entertainment', value: 'arts-entertainment' },
          { title: 'Automotive Services', value: 'automotive-services' },
          { title: 'Building Services', value: 'building-services' },
          { title: 'Construction', value: 'construction' },
          { title: 'Education', value: 'education' },
          { title: 'Healthcare', value: 'healthcare' },
          { title: 'Hospitality', value: 'hospitality' },
          { title: 'Manufacturing', value: 'manufacturing' },
          { title: 'Public Administration', value: 'public-administration' },
          { title: 'Retail Trade', value: 'retail-trade' },
          { title: 'Transportation', value: 'transportation' },
          { title: 'Utilities', value: 'utilities' },
          { title: 'Waste & Environmental', value: 'waste-environmental' },
          { title: 'Wholesale Trade', value: 'wholesale-trade' },
          { title: 'Business Support Services', value: 'business-support-services' },
          { title: 'Equipment Repair', value: 'equipment-repair' },
          { title: 'Facilities Management', value: 'facilities-management' },
          { title: 'Information/Telecom', value: 'information-telecom' },
          { title: 'Laundry & Drycleaning', value: 'laundry-drycleaning' },
          { title: 'Mining', value: 'mining' },
          { title: 'Professional Services', value: 'professional-services' },
          { title: 'Real Estate', value: 'real-estate' },
          { title: 'Staffing & Employment', value: 'staffing-employment' },
          { title: 'Warehouse', value: 'warehouse' },
          { title: 'Personal Services', value: 'personal-services' },
          { title: 'Security Services', value: 'security-services' },
        ],
      },
    }),
    defineField({ name: 'featured', title: 'Featured', type: 'boolean', description: 'Show in featured section on resources hub', initialValue: false }),
    defineField({ name: 'downloadUrl', title: 'Download URL', type: 'url', description: 'Optional: link to downloadable file' }),
    defineField({ name: 'publishedAt', title: 'Published At', type: 'datetime', initialValue: () => new Date().toISOString() }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'resourceType', media: 'coverImage' },
  },
})
